package dev.ikna.ui.text

internal val STRINGS_DE: Map<String, String> = mapOf(
    "app.001" to "Erinnerung", "app.002" to "Eine Erinnerung pro Tag, nur wenn das Minimum noch nicht erledigt ist",
    "font.001" to "Datei konnte nicht gelesen werden", "font.002" to "Die Datei ist für eine Schrift zu groß",
    "font.003" to "Schrift konnte nicht gespeichert werden", "font.004" to "Schrift konnte nicht gespeichert werden",
    "font.005" to "Das ist keine Schriftdatei", "font.006" to "Das ist eine .ttc-Schriftsammlung; benötigt wird eine einzelne .ttf- oder .otf-Schrift",
    "font.007" to "Das ist eine .woff-Webschrift; Android kann sie nicht lesen. Verwende .ttf oder .otf",
    "font.008" to "Das ist keine Schriftdatei", "font.009" to "Die Schriftdatei ist beschädigt",
    "font.010" to "Die Schriftdatei ist unvollständig", "font.011" to "Die Schriftdatei ist unvollständig",
    "font.012" to "Die Schrift hat keine Zeichentabelle", "font.013" to "Die Schrift enthält keine Buchstaben",
    "deckrepo.001" to "Dein eigenes Deck", "stats.001" to "Statistik", "stats.002" to "LETZTE 30 TAGE",
    "stats.003" to "Jede Markierung ist ein Lerntag, heute steht rechts. Ein ausgelassener Tag setzt nichts zurück: Hier gibt es keine Serie, die brechen kann.",
    "stats.004" to "TAGESNORM", "stats.005" to "Karten pro Tag. Aus deinen letzten Tagen berechnet und automatisch neu bestimmt.",
    "stats.006" to "Eine Startschätzung, keine Messung. Dein eigener Wert wird nach mindestens drei Lerntagen berechnet.",
    "stats.007" to "WÖRTER IM GEDÄCHTNIS", "stats.008" to "HEUTE BEANTWORTET",
    "stats.009" to "Wörter werden getrennt von Chunks gezählt: Ein Wort erscheint in mehreren Wendungen und hält besser als jede einzelne.",
    "stats.010" to "IN 14 TAGEN FÄLLIG", "stats.011" to "So viele Karten werden fällig. Wächst irgendwo ein Berg, kommen an diesen Tagen keine neuen Chunks hinzu.",
    "stats.012" to "BEHALTENSRATE", "stats.013" to "Mindestens 20 Wiederholungen sind nötig, damit dies ein Messwert ist. Bisher: ",
    "stats.014" to "Von ", "stats.015" to " Wiederholungen in diesem Monat erinnert: ",
    "stats.016" to " %. Nur Wiederholungen zählen; eine erste Begegnung kann nicht vergessen werden.",
    "stats.017" to "Der Plan zielt auf etwa 90 %. Unter 80 % sind die Abstände zu lang. Die Last passt sich an; bleibt es wochenlang so, wähle eine kleinere Norm.",
    "stats.018" to "Der Plan zielt auf etwa 90 %. Über 95 % gibt es mehr Wiederholungen als nötig; längere Abstände würden reichen.",
    "stats.019" to "Der Plan zielt auf etwa 90 % und du liegst in diesem Bereich. Nichts muss geändert werden.",
    "stats.020" to "MINUTEN HEUTE", "stats.021" to "DIESE WOCHE",
    "stats.022" to "Nur Zeit mit einer sichtbaren Karte zählt. Eine Karte dauert bei dir etwa ", "stats.023" to " Sek.",
    "stats.024" to "Nur Zeit mit einer sichtbaren Karte zählt; Pausen mit abgelegtem Telefon nicht.",
    "stats.025" to "WANN ES AM BESTEN LÄUFT", "stats.026" to "Am besten erinnerst du dich gegen ",
    "stats.027" to ". Das ist kein Befehl, genau dann zu lernen; zu dieser Stunde fällt es dir nur leichter. Eine Erinnerung eine Stunde vorher ist sinnvoll.",
    "stats.028" to "Noch zu früh für eine Uhrzeit: Mindestens 12 Wiederholungen innerhalb derselben Stunde sind nötig. Helle Balken haben noch zu wenig Daten.",
    "stats.029" to "BLEIBT NICHT HÄNGEN", "stats.030" to "Bisher keine: Nichts wurde viermal oder öfter vergessen.",
    "stats.031" to "Rechts steht, wie oft die Wendung vergessen wurde. Es geht um die Wendung, nicht um dich: Meist ist sie zu lang oder die Übersetzung passt nicht. Sie erscheint seltener.",
    "stats.032" to "HEUTE",
    "set.001" to "Datei konnte nicht geöffnet werden", "set.002" to "Datei konnte nicht geöffnet werden", "set.003" to "Schrift angewendet: ",
    "set.004" to "Ohne Benachrichtigungsberechtigung kommt keine Erinnerung", "set.005" to "Die Einstellungsdatei ist beschädigt",
    "set.006" to "Einstellungen wiederhergestellt", "set.007" to "Einstellungen wiederhergestellt. Die Schrift «",
    "set.008" to "» muss erneut gewählt werden; deine Schriftdatei ist nicht Teil der Sicherung.",
    "set.009" to "Antworten hinzugefügt: ", "set.010" to " · neu berechnet ", "set.011" to " · übersprungen ",
    "set.012" to "Einstellungen", "set.013" to "Last", "set.015" to "AUTO", "set.016" to "MANUELL",
    "set.017" to "JETZT · ", "set.018" to "KARTEN PRO TAG", "set.019" to "Aussehen", "set.020" to "Animationen",
    "set.022" to "Vibration", "set.024" to "Sprache", "set.026" to "Sprachausgabe",
    "set.027" to "Es spricht die bereits installierte Sprach-Engine. Nichts wird geladen oder gesendet; Stimmen, die Internet brauchen, erscheinen nicht in der Liste.",
    "set.028" to "Vorlesen", "set.029" to "Das Tonsymbol erscheint nur, wenn es die Antwort nicht verrät",
    "set.030" to "Stimmen auf dem Telefon werden geprüft…",
    "set.031" to "Auf dem Telefon ist keine Sprach-Engine. Eine Offline-Engine wie RHVoice oder SherpaTTS aus F-Droid genügt. Kehre nach der Installation zurück.",
    "set.032" to "EINSTELLUNGEN DER SPRACH-ENGINE", "set.033" to "Dieser Bereich der Telefoneinstellungen wurde nicht gefunden",
    "set.034" to "Eine Engine ist vorhanden, aber ohne Offline-Stimmen für diese Sprachen. Lade sie einmal; danach funktionieren sie ohne Netz.",
    "set.035" to "STIMMEN INSTALLIEREN", "set.036" to "Die Engine kann Stimmen nicht selbst laden; öffne ihre Einstellungen",
    "set.037" to "keine Offline-Stimme für diese Sprache", "set.038" to "STANDARD",
    "set.039" to "Der erste Ton nach dem Start kann einige Sekunden dauern, während die Engine aufwacht. Die nächste Karte wird vorab vorbereitet.",
    "set.040" to "Schrift", "set.041" to "Deine .ttf- oder .otf-Schrift für Karten und Überschriften. Technische Beschriftungen bleiben nichtproportional. Die Datei wird vor dem Anwenden geprüft, damit eine defekte Schrift nicht alle Bildschirme blockiert.",
    "set.042" to "JETZT · SYSTEM", "set.043" to "JETZT · ", "set.044" to "DATEI WÄHLEN", "set.045" to "ZURÜCKSETZEN",
    "set.046" to "Systemschrift wiederhergestellt", "set.047" to "Erinnerung", "set.049" to "Erinnere mich", "set.050" to "um ", "set.051" to "aus",
    "set.052" to "Daten", "set.053" to "Das Antwortprotokoll ist das Einzige, was nicht rekonstruiert werden kann. Alles andere wird daraus neu berechnet.",
    "set.054" to "Wöchentlich automatisch exportieren", "set.055" to "In den Ordner Documents/ikna", "set.056" to "EXPORTIEREN",
    "set.057" to "Datei konnte nicht gespeichert werden", "set.058" to "Einstellungen gespeichert. Das Protokoll ist noch leer; nichts zu exportieren.",
    "set.059" to "Protokoll und Einstellungen in Documents/ikna gespeichert", "set.060" to "WIEDERHERSTELLEN",
    "set.063" to "Selten", "set.065" to "AUSBLENDEN", "set.066" to "ANZEIGEN",
    "set.067" to "WORTSCHICHT NEU AUFBAUEN", "set.068" to "Wortschicht aus dem Protokoll neu aufgebaut",
    "set.069" to "TECHNISCHER BILDSCHIRM", "set.070" to "NEU ANFANGEN", "set.071" to "Alles löschen",
    "set.072" to "Vollständiges Zurücksetzen: Karten, Termine, Statistik, Antwortprotokoll und Einstellungen. Die App startet wie frisch installiert neu. Vorher wird das Protokoll exportiert.",
    "set.073" to "WIRKLICH ALLES LÖSCHEN", "set.074" to "DATEN LÖSCHEN", "set.075" to "Drücke erneut, wenn du es wirklich meinst. Es gibt kein Rückgängig.",
    "set.076" to "der zweite Druck löscht sofort", "set.077" to "zweimal drücken", "set.078" to "Neu anfangen?",
    "set.079" to "Kartentermine, Statistik und Wortschicht werden zurückgesetzt. Das Antwortprotokoll bleibt und kann alles über „Wiederherstellen“ zurückbringen.",
    "set.080" to "NEU ANFANGEN", "set.081" to "Statistik zurückgesetzt", "set.082" to "ABBRECHEN",
    "set.083" to "HINTERGRUND", "set.084" to "TEXT", "set.085" to "GEDÄMPFT", "set.086" to "AKZENT",
    "set.087" to "KONTRAST · TEXT ", "set.088" to " · GEDÄMPFT ", "set.089" to " · AKZENT ",
    "set.090" to "etwas ist auf seinem Hintergrund schlecht lesbar; die Farbe wird trotzdem angewendet",
    "set.091" to "LAST", "set.092" to "AUSSEHEN", "set.093" to "SPRACHE", "set.094" to "SPRACHAUSGABE",
    "set.095" to "SCHRIFT", "set.096" to "ERINNERUNG", "set.097" to "DATEN", "set.098" to "SELTEN",
    "set.099" to "SYSTEM", "set.100" to "РУССКИЙ", "set.101" to "DUNKEL", "set.102" to "HELL", "set.103" to "EIGEN",
    "set.104" to "POLNISCH", "set.105" to "RUSSISCH", "set.106" to "ENGLISCH", "set.107" to "DEUTSCH",
    "set.108" to "SPANISCH", "set.109" to "FRANZÖSISCH", "set.110" to "Schrift", "set.114" to "PALETTE",
    "set.116" to "GLUT", "set.117" to "BIBLIOTHEK", "set.118" to "TINTE", "set.119" to "PFLAUME", "set.120" to "NULL",
    "set.121" to "NEUTRAL", "set.125" to "ROSE", "set.126" to "REIF", "set.127" to "PHOSPHOR", "set.141" to "ULTRAVIOLETT", "set.142" to "LAGUNE", "set.143" to "KOBALT", "set.122" to "BELEUCHTUNG",
    "set.128" to "ALLE SPRACHEN", "set.130" to "Telefonstimme", "set.131" to "Liest Sprachen, die keines deiner Modelle abdeckt",
    "set.132" to "Immer sprechen", "set.133" to "Die Karte liest sich bei jedem Erscheinen vor", "set.134" to "Die Karte liest sich nur beim ersten Kontakt vor",
    "set.135" to "Aus dem Umlauf entfernte Karten: ", "set.136" to "Zurückholen", "set.137" to "Die Karten sind zurück",
    "set.138" to "Aktualisierungen", "set.139" to "Die App wird aus einer Datei installiert; nur sie selbst kann dich auf eine neue Version hinweisen.",
    "set.140" to "AKTUALISIERUNG", "set.123" to "BETA", "set.124" to "Beta und standardmäßig aus: Die Telefon-Engine bestimmt den Klang, und eine schlechte Stimme ist schlimmer als Stille.",
    "dbg.001" to "← ZURÜCK", "dbg.002" to "ANTWORTPROTOKOLL EXPORTIEREN", "dbg.003" to "Datei: Documents/ikna/",
    "dbg.004" to "Datei konnte nicht gespeichert werden", "dbg.005" to "WORTSCHICHT NEU AUFBAUEN", "dbg.006" to "Wortschicht neu aufgebaut",
    "dbg.007" to "HEUTIGEN PLAN NEU AUFBAUEN", "dbg.008" to "Heutiger Plan neu aufgebaut", "dbg.009" to "Reglerentscheidungen nach Tag",
    "dbg.010" to " neu=", "dbg.011" to " fällig=", "dbg.012" to " Prognose3T=", "dbg.013" to " Rückstand=", "dbg.014" to " Genauigkeit=", "dbg.015" to " Spielraum=",
    "deck.001" to "Keine einzige Zeile konnte gelesen werden", "deck.002" to "Chunks hinzugefügt: ", "deck.003" to ", übersprungen ",
    "deck.004" to "Decks", "deck.005" to "Noch keine Decks. Das Plus unten enthält den KI-Prompt und einen Platz zum Einfügen.",
    "deck.006" to "Datei wird gelesen…", "deck.007" to "HEUTE", "deck.008" to "nichts wartet", "deck.009" to "heute ", "deck.010" to "heute nichts",
    "deck.014" to "Karten", "deck.015" to "Karte", "deck.016" to "Karten", "deck.017" to "Karten", "deck.018" to " · <1 Min.", "deck.019" to " Min.",
    "add.001" to "Neues Deck", "add.002" to "Ein Deck ist Klartext. Eine Zeile ist eine Karte: Wendung, Beispielsatz und Übersetzung, getrennt durch |.",
    "add.003" to "Kopiere den Prompt und sende ihn an eine beliebige KI.", "add.004" to "Nenne Sprache und Thema: „Polnisch, Kochen, 100 Karten“.",
    "add.005" to "Kopiere die ganze Antwort oder speichere sie als Datei.", "add.006" to "Kehre zurück und füge den Text ein oder wähle die Datei.",
    "add.007" to "Prompt kopieren", "add.008" to "Prompt als Datei speichern", "add.009" to "Prompt kopiert", "add.010" to "Prompt gespeichert",
    "add.011" to "Prompt konnte nicht gespeichert werden", "add.012" to "Deckzeilen hier einfügen", "add.013" to "Beispiel einfügen",
    "add.014" to "Aus Text hinzufügen", "add.015" to "Datei wählen", "add.016" to "WENDUNG | SATZ DAMIT | ÜBERSETZUNG",
    "add.017" to "lesen…", "add.018" to "Die Datei ist für ein Deck zu groß", "add.019" to "Datei konnte nicht gelesen werden", "add.020" to "Füge zuerst Text ein",
    "add.021" to "Karten hinzugefügt: ", "add.022" to ", Zeilen übersprungen: ", "add.023" to "Zeile ", "add.024" to " — ", "add.025" to "Keine Zeile war verwendbar", "add.026" to "Fertig",
    "add.027" to "sich gewöhnen an|Es dauert, sich an den Lärm zu gewöhnen.|vertraut werden\\naufpassen auf|Kannst du auf meine Tasche aufpassen?|im Auge behalten",
    "add.028" to "Beispiel eingefügt", "add.029" to "Leeren", "add.030" to "Mein Deck", "add.031" to "die Zeile hat nicht drei Teile",
    "add.032" to "ein Feld ist leer", "add.033" to "die Wendung fehlt im Satz", "add.034" to "die Zeile ist zu lang", "add.035" to "diese Wendung wurde bereits verwendet",
    "share.001" to "teilen", "share.002" to "Deck senden", "share.003" to "Teilen fehlgeschlagen", "share.004" to "dieses Deck hat noch nichts zum Senden",
    "dp.001" to "Aktiv", "dp.002" to "Ausgeschaltet", "dp.003" to "Decksprache",
    "dp.004" to "Nur für die Stimme. Ein importiertes Deck beginnt ohne Sprache und kann erst nach der Auswahl vorgelesen werden.",
    "dp.005" to "keine Stimme", "dp.006" to "Deck senden", "dp.007" to "Deck löschen", "dp.008" to "Zum Bestätigen erneut tippen",
    "dp.009" to "Karten und Zeitplan dieses Decks verschwinden. Antworten bleiben in der Statistik; das Protokoll wird nie umgeschrieben.",
    "dp.010" to "Karten hinzufügen", "dp.011" to "Hinzufügen…", "dp.013" to "Deckname",
    "add.036" to "so funktioniert es", "add.037" to "ausblenden", "add.038" to "Sprache der Karten", "add.039" to "Nur für die Stimme; später auf der Deckseite änderbar.",
    "add.040" to "Was das Modell erstellen soll", "add.041" to "Anzahl der Karten", "add.042" to "Sprache der Bedeutungen",
    "add.043" to "Anfang", "add.044" to "kann ein Gespräch führen", "add.045" to "fließend", "add.046" to "Niveau",
    "add.047" to "Thema oder Situation", "add.048" to "zum Beispiel Cafés und Essen bestellen", "add.049" to "Die Antworten landen im Prompt; im Chat muss nichts mehr eingegeben werden.",
    "add.050" to "Prüfenswerte Zeilen: ", "add.051" to "die Bedeutung wiederholt den Begriff", "add.052" to "eine ausweichende Formulierung",
    "add.053" to "diese Bedeutung kam oben schon vor", "add.054" to "enthält Zahlen; mit der Quelle prüfen", "add.055" to "Was wird gelernt",
    "add.056" to "eine Sprache", "add.057" to "ein Fach", "add.058" to "Ein Fachdeck wird nicht vorgelesen und verlangt kein Sprechen; nur Erkennen und Erinnern.",
    "add.059" to "etwas Vorwissen", "add.060" to "Fach und Abschnitt", "add.061" to "zum Beispiel Neurowissenschaft, synaptische Plastizität",
    "add.062" to "Sprache der Karten", "add.063" to "Aus Zwischenablage einfügen", "add.064" to "Die Zwischenablage enthält keinen Text",
    "add.065" to "Zeilen", "add.066" to "Zeichen", "add.067" to "TEXT ANZEIGEN", "add.068" to "TEXT AUSBLENDEN", "add.069" to "und weitere Zeilen: ",
    "add.070" to "Zeilenumbrüche gingen beim Einfügen verloren und diese Zeile konnte nicht rekonstruiert werden. Nutze „Aus Zwischenablage einfügen“; Tastaturen kürzen große Texte.",
    "add.071" to "Der Text war länger als das Limit und wurde gekürzt. Teile das Deck in zwei Teile.", "add.072" to "Wenn es kein fertiges Deck gibt",
    "add.073" to "Der optionale Weg: Ein Modell schreibt das Deck. Das Ergebnis muss geprüft werden; für Sprachen ist der Katalog besser.", "add.074" to "MODELL-METHODE",
    "card.002" to "irgendwo tippen", "card.003" to "← WEISS ICH NICHT", "card.004" to "WEISS ICH →",
    "sess.001" to "einen Moment…", "sess.003" to "MINIMUM ERLEDIGT", "sess.004" to "Deck beendet", "sess.005" to "Das war alles für heute",
    "sess.006" to "Heute keine Karten", "sess.007" to "Nichts mehr zu wiederholen; der Rest ist noch nicht fällig", "sess.008" to "ERNEUT PRÜFEN",
    "sess.009" to "ETWAS MEHR +5", "sess.010" to "nur Wiederholungen, keine neuen Chunks", "sess.011" to "diese Antwort kann nicht mehr rückgängig gemacht werden",
    "sess.012" to "Antwort gespeichert", "sess.013" to "RÜCKGÄNGIG", "sess.014" to "OK", "sess.015" to "erkennen", "sess.016" to "ergänzen", "sess.017" to "laut sagen",
    "sess.018" to "Der Tagesplan ist geschlossen. Neue Chunks kommen morgen von selbst.", "sess.019" to "Erster Tag: Wir nehmen sehr wenig.",
    "sess.020" to "Alles wiederholt; die nächsten sind noch nicht fällig.", "sess.021" to "Es stehen bereits viele Wiederholungen an; neue Wörter warten.",
    "sess.022" to "Zuerst das Angesammelte, dann Neues.", "sess.023" to "Nach einer Pause zuerst mit Altem aufwärmen.",
    "sess.024" to "Die Woche war ruhig: Neues wartet, Termine sind verschoben, es gibt keine Schulden.", "sess.025" to "Zu spät für neue Chunks; wir sehen sie morgens. Wiederholungen bleiben.",
    "sess.026" to "Nichts Neues, bis das Alte sitzt.", "sess.027" to "Rückkehrmodus: einige kurze Tage, keine Schulden.", "sess.028" to "Mindestens ein neuer Chunk, damit es weitergeht.",
    "sess.029" to "Hier gibt es keine neuen Chunks mehr; alle sind bekannt. Wiederholungen kommen weiter, für neues Material brauchst du ein weiteres Deck.",
    "sess.030" to "nächste: heute um ", "sess.031" to "nächste: morgen um ", "sess.032" to "nächste: in ", "sess.033" to "Tagen", "sess.034" to "Tag",
    "sess.035" to "Tagen", "sess.036" to "Tagen", "sess.037" to " · <1 MIN", "sess.038" to " MIN", "sess.039" to "Karten", "sess.040" to "Karte",
    "sess.041" to "Karten", "sess.042" to "Karten", "sess.043" to "Gestern war lang; heute wird leichter und ohne Neues.",
    "sess.044" to "ALS FALSCH MARKIEREN", "sess.045" to "Aus dem Umlauf entfernt. Der Fehler wurde nicht in deine Statistik geschrieben.",
    "sess.046" to "den Begriff", "sess.047" to "aus dem Gedächtnis",
    "onb.001" to "In Wendungen, nicht in Wörtern", "onb.002" to "Fertige Chunks sind enthalten. Neue kommen von selbst; nichts muss einzeln eingegeben werden.",
    "onb.003" to "Auslassen ist kein Versagen", "onb.004" to "Nach einem fehlenden Tag oder einer Woche wartet kein Berg. Altes kehrt langsam zurück; Neues nur, wenn Platz ist.",
    "onb.005" to "Das Minimum ist eine Karte", "onb.006" to "Eine Karte schließt den Tag. „Etwas mehr“ macht morgen nicht schwerer.",
    "onb.007" to "KARTEN WERDEN VORBEREITET…", "onb.008" to "WEITER", "onb.009" to "START", "onb.010" to "ÜBERSPRINGEN",
    "onb.011" to "Links und rechts", "onb.012" to "Wische links, wenn du es nicht weißt, rechts, wenn du es weißt. Tippen unten macht dasselbe. Eine Antwort kann direkt danach rückgängig gemacht werden.",
    "speaker.001" to "AUSGEZEICHNET", "speaker.002" to "GUT", "speaker.003" to "NORMAL", "speaker.004" to "NIEDRIG",
    "remind.001" to "Eine Karte", "remind.002" to "Eine reicht, um den Tag zu schließen",
    "a11y.001" to "Zurück", "a11y.002" to "Einstellungen", "a11y.003" to "Statistik", "a11y.004" to "Deck hinzufügen",
    "a11y.005" to "Vorlesen", "a11y.006" to "Deck aktiv", "a11y.007" to "Diese Zahl erklären", "a11y.008" to "Weiß ich nicht", "a11y.009" to "Weiß ich",
    "a11y.010" to "Deck-Einstellungen",
    "voice.001" to "Stimme", "voice.002" to "Liest gerade", "voice.003" to "Telefonstimme", "voice.004" to "Diese Version enthält keine Modell-Engine; nur die Telefonstimme liest",
    "voice.005" to "Ein Modell ist installiert, wurde aber nicht geladen. Die Telefonstimme liest", "voice.006" to "Kein Modell. Die Telefonstimme liest",
    "voice.007" to "Modell wird geprüft…", "voice.008" to "Modell geladen und bereit", "voice.010" to "Stimme testen", "voice.011" to "Deine Modelle",
    "voice.012" to "Du bringst das Modell mit: einen Kokoro- oder Piper-Ordner vom Telefon. Nichts wird heruntergeladen.", "voice.013" to "Modell entfernen",
    "voice.014" to "Modellsprache", "voice.015" to "Beliebig", "voice.016" to "Diese Version hat keine Engine. Dein Modell funktioniert hier nicht; nimm die mit voice markierte Version.",
    "voice.017" to "Weiteres Modell hinzufügen", "voice.018" to "Dateien kopiert: ", "voice.019" to "Das sieht nicht wie ein Modell aus: keine .onnx-Datei im Ordner",
    "voice.020" to "Der gewählte Ordner liegt eine Ebene zu hoch. Öffne ihn und wähle den Modellordner", "voice.021" to "Mehrere Modelle in einem Ordner. Lass nur eines",
    "voice.022" to "Keine tokens.txt. Nimm die sherpa-onnx-Ausgabe, nicht die rohen Piper-Dateien", "voice.023" to "Kopieren fehlgeschlagen: ",
    "voice.024" to "Modell hinzugefügt", "voice.025" to "Vorlesen ist aus; der Schalter oben aktiviert es",
    "voice.026" to "Modelle liegen auf der sherpa-onnx-Releaseseite unter tts-models. Kokoro spricht Englisch; Piper deckt fast jede Sprache ab.",
    "voice.027" to "Keine voices.bin. Der Kokoro-Download endete zu früh", "voice.028" to "Nichts zum Aussprechen: weder espeak-ng-data noch Lexikon",
    "voice.029" to "Modell hinzufügen", "voice.030" to "Karten vorlesen", "voice.031" to "Solange dies aus ist, bleiben Karten stumm, mit oder ohne Modell",
    "voice.032" to "Wer welches Deck liest", "voice.033" to "das Modell liest es", "voice.034" to "die Telefonstimme liest es",
    "voice.035" to "niemand: Das Modell kennt diese Sprache nicht und das Telefon hat keine Stimme", "voice.036" to "Ein Modell spricht eine Sprache. Die Decksprache wird beim Import gefragt und kann im Deck geändert werden.",
    "voice.037" to "KEINE SPRACHE", "voice.038" to "ausgeschaltet", "voice.039" to "Stimmennummer", "voice.040" to "Ein Modell pro Sprache",
    "voice.041" to ".tar.bz2-Archiv hinzufügen", "voice.042" to "Das ist kein Modellarchiv", "voice.043" to "Zu wenig Platz: Entpackt ist ein Modell etwa dreimal so groß wie das Archiv",
    "voice.044" to "Die App entpackt das Archiv selbst", "voice.045" to "Sprache aus dem Modellnamen:", "voice.046" to "ANDERE SPRACHE",
    "voice.047" to "Nur das Modell kennt seine Stimmenzahl: Teste die Stimme, dann erscheint die Zahl hier.", "voice.048" to "Geschwindigkeit", "voice.049" to "Entpacken:",
    "voice.050" to "Ein großes Modell braucht Minuten zum Entpacken; der Telefonprozessor verarbeitet bzip2.", "voice.051" to "Du kannst diesen Bildschirm verlassen; die Installation läuft weiter. Lege die App nicht lange weg.",
    "look.001" to "Erscheinungsbild", "look.002" to "Buchstaben und Farbe des Quadrats in der Deckliste. Nur für dich; beim Teilen werden nur die Karten gesendet.",
    "look.003" to "Farbe des Quadrats", "look.004" to "Ein oder zwei Zeichen. Leer bestimmt das Quadrat sie selbst.", "bar.001" to "Das ikna-Zeichen", "bar.003" to "Für die linke Hand",
    "upd.001" to "AKTUALISIERUNG VERFÜGBAR", "upd.002" to "Größe: ", "upd.003" to "MB", "upd.004" to "Neu:", "upd.005" to "AKTUALISIEREN", "upd.006" to "ÜBERSPRINGEN",
    "upd.007" to "Die App lädt die Datei selbst; Balken und Prozent stehen hier. Android installiert die neue Version über die alte, Karten und Fortschritt bleiben.",
    "upd.008" to "Nach Aktualisierungen suchen", "upd.009" to "Eine Anfrage an die Releaseseite, höchstens einmal täglich. Nichts wird gesendet. Ausgeschaltet wird keine Verbindung geöffnet.",
    "upd.010" to "JETZT PRÜFEN", "upd.011" to "Installiert: ", "upd.012" to "Nichts Neueres. Ohne Netz ist die Prüfung nur fehlgeschlagen; die App kann beides nicht unterscheiden.",
    "upd.013" to "RELEASESEITE", "upd.014" to "PRÜFEN…", "upd.015" to "Übersprungen: ", "upd.016" to "Aktualisieren auf ", "upd.017" to "DOWNLOAD",
    "upd.018" to "Die Datei ist bereit. Android installiert sie über die alte Version; Karten, Fortschritt und Einstellungen bleiben.", "upd.019" to "ABBRECHEN", "upd.020" to "INSTALLIEREN",
    "upd.021" to "Android verlangt die Erlaubnis, Apps aus dieser Quelle zu installieren. Die Datei ist bereits geladen und bleibt gespeichert.", "upd.022" to "ERLAUBEN",
    "upd.023" to "Download fehlgeschlagen: Verbindung abgebrochen oder Datei unvollständig. Erneut versuchen oder im Browser laden.", "upd.024" to "ERNEUT VERSUCHEN", "upd.025" to "IM BROWSER",
    "cat.001" to "Deckkatalog", "cat.002" to "Decks aus Tatoeba; Wiktionary dient beim Erstellen nur zum Trennen von Wortformen. Das Telefon lädt die fertige Datei. Lizenz und Urheber stehen vor dem Download und bleiben in den Karten.",
    "cat.003" to "LISTE WIRD GELADEN…", "cat.004" to "Die Liste kam nicht an: kein Netz oder Katalog nicht erreichbar. Nichts ist kaputt; eingebautes Deck und Modellerstellung bleiben verfügbar.",
    "cat.005" to "KATALOGSEITE", "cat.006" to "ERNEUT VERSUCHEN", "cat.007" to "Lernsprache", "cat.008" to "Bedeutungen auf", "cat.009" to "Thema", "cat.010" to "Niveau", "cat.011" to "ALLE",
    "cat.012" to "Dieses Paar ist gut abgedeckt: viele Sätze und große Decks.", "cat.013" to "Dieses Paar ist dünn: Der Korpus enthält wenige Sätze. Das ist eine Grenze der Quelle, nicht der App.",
    "cat.014" to "Für dieses Paar gibt es noch nichts. Das README zeigt die Abdeckung aller Paare.", "cat.015" to "Karten", "cat.016" to "Lizenz: ", "cat.017" to "Quelle: ",
    "cat.018" to "HERUNTERLADEN", "cat.019" to "DOWNLOAD", "cat.020" to "Download fehlgeschlagen: Verbindung abgebrochen oder Datei unvollständig. Nichts wurde installiert.",
    "cat.021" to "Die Datei kam an, aber keine Karte konnte erstellt werden. Kein Deck wurde hinzugefügt.", "cat.022" to "Fertig. Karten im Deck: ", "cat.023" to "DECK WIRD ERSTELLT…",
    "cat.024" to "MB", "cat.025" to "CC BY-SA: Ein abgeleitetes und weitergegebenes Deck behält dieselbe Lizenz. Das Lernen selbst verpflichtet zu nichts.", "cat.026" to "Liste erstellt: ",
    "cat.027" to "Anfänger", "cat.028" to "Mittelstufe", "cat.029" to "Fortgeschritten", "cat.030" to "Keine Treffer für diese Filter.",
    "cat.031" to "Ein fertiges Deck", "cat.032" to "Wenn ein Modell zu umständlich ist: Deck aus dem Katalog, von Menschen geschriebene Sätze, offene Lizenz und genannter Urheber.",
    "cat.033" to "KATALOG ÖFFNEN", "cat.034" to "BEREITS GELADEN", "cat.035" to "noch einmal laden", "cat.036" to "BEISPIELE ANZEIGEN",
    "cat.037" to "BEISPIELE WERDEN GELADEN…", "cat.038" to "BEISPIELE ERNEUT LADEN", "cat.039" to "BEISPIELE AUS DEM DECK", "cat.040" to "KARTE ",
    "a11y.011" to "Decks durchsuchen", "src.001" to "Quelle · ", "src.002" to "Ist diese Karte falsch?",
    "src.003" to "Die Karte wird ausgeblendet und ein fertiger Bericht mit Text und Quellenlink kopiert. Er kann in GitHub Issues eingefügt werden.",
    "src.004" to "AUSBLENDEN UND KOPIEREN", "src.005" to "ABBRECHEN", "src.006" to "Karte ausgeblendet · Bericht kopiert", "src.007" to "QUELLE",
    "search.001" to "Decks durchsuchen", "search.002" to "Sucht nur in Decks, die auf diesem Telefon installiert sind. Kein Netzwerk.",
    "search.003" to "Wendung, Satz oder Übersetzung", "search.004" to "SUCHEN", "search.005" to "SUCHE…", "search.006" to "Gib mindestens zwei Zeichen ein.",
    "search.007" to "In den installierten Decks wurde nichts gefunden.", "search.008" to "Die ersten 80 Treffer werden gezeigt; präzisiere die Suche für eine kürzere Liste.",
    "search.009" to "Die Suche wurde nicht abgeschlossen. Keine Daten wurden geändert; versuche es erneut.", "search.010" to "DECK · ",
    "mig.001" to "Zeitplan wird aktualisiert", "mig.002" to "Decks und Verlauf bleiben. Antworten werden einmal mit FSRS-6 neu abgespielt.",
    "mig.003" to "Der Zeitplan wurde nicht aktualisiert", "mig.004" to "Nichts wurde gelöscht. Die Neuberechnung kann sicher wiederholt werden.", "mig.005" to "ERNEUT VERSUCHEN",
    "diag.001" to "Diagnose", "diag.002" to "Nur technische Übersicht: keine Decknamen, Kartentexte, Antwortverläufe oder Kennungen. Nichts wird gesendet; der Bericht bleibt bis zum Kopieren auf dem Telefon.",
    "diag.003" to "DIAGNOSE ANZEIGEN", "diag.004" to "DIAGNOSE AUSBLENDEN", "diag.005" to "SAMMELN…", "diag.006" to "ÜBERSICHT KOPIEREN",
    "diag.007" to "Diagnose kopiert", "diag.008" to "Diagnose konnte nicht erstellt werden",
)
