package dev.ikna.ui.text

internal val STRINGS_ES: Map<String, String> = mapOf(
    "app.001" to "Recordatorio",
    "app.002" to "Un recordatorio al día, solo si aún no se ha completado el mínimo",
    "font.001" to "No se pudo leer el archivo",
    "font.002" to "El archivo es demasiado grande para una fuente",
    "font.003" to "No se pudo guardar la fuente",
    "font.004" to "No se pudo guardar la fuente",
    "font.005" to "Ese archivo no es una fuente",
    "font.006" to "Es una colección de fuentes .ttc; se necesita una sola fuente .ttf u .otf",
    "font.007" to "Es una fuente web .woff; Android no puede leerla, usa .ttf u .otf",
    "font.008" to "Ese archivo no es una fuente",
    "font.009" to "El archivo de fuente está dañado",
    "font.010" to "El archivo de fuente está incompleto",
    "font.011" to "El archivo de fuente está incompleto",
    "font.012" to "La fuente no tiene tabla de caracteres",
    "font.013" to "La fuente no contiene letras",
    "deckrepo.001" to "Tu propio mazo",
    "stats.001" to "Estadísticas",
    "stats.002" to "ÚLTIMOS 30 DÍAS",
    "stats.003" to "Cada marca es un día con una sesión; hoy está a la derecha. Saltarse un día no pone nada a cero ni rompe nada: aquí no hay rachas.",
    "stats.004" to "NORMA DIARIA",
    "stats.005" to "Tarjetas al día. Se calcula a partir de tus últimos días y se recalcula automáticamente.",
    "stats.006" to "Es una estimación inicial, no una medición. Calcularé tu cifra cuando haya al menos tres días con sesiones; antes sería inventada.",
    "stats.007" to "PALABRAS EN LA MEMORIA",
    "stats.008" to "RESPONDIDAS HOY",
    "stats.009" to "Las palabras se cuentan aparte de los fragmentos: una palabra aparece en varias frases y se conserva mejor que cualquiera de ellas.",
    "stats.010" to "VENCEN EN 14 DÍAS",
    "stats.011" to "Cuántas tarjetas vencerán. Si se forma una montaña, esos días no se añadirán fragmentos nuevos.",
    "stats.012" to "RETENCIÓN",
    "stats.013" to "Se necesitan al menos 20 repasos para que sea una cifra y no una suposición. Por ahora hay ",
    "stats.014" to "De ",
    "stats.015" to " repasos este mes, se recordaron ",
    "stats.016" to "%. Solo cuentan los repasos: un primer encuentro no puede olvidarse.",
    "stats.017" to "La planificación apunta a cerca del 90 %. Por debajo del 80 %, los intervalos son demasiado largos para ti. La carga se ajusta sola, pero si dura semanas, elige una norma menor.",
    "stats.018" to "La planificación apunta a cerca del 90 %. Por encima del 95 % hay más repasos de los necesarios: la memoria admitiría intervalos mayores y ahorrarías minutos.",
    "stats.019" to "La planificación apunta a cerca del 90 % y ahora todo está dentro de ese margen. No hace falta tocar nada.",
    "stats.020" to "MINUTOS HOY",
    "stats.021" to "ESTA SEMANA",
    "stats.022" to "Solo cuenta el tiempo con una tarjeta en pantalla; las pausas con el teléfono apartado no entran. Cada tarjeta te lleva unos ",
    "stats.023" to " s.",
    "stats.024" to "Solo cuenta el tiempo con una tarjeta en pantalla; las pausas con el teléfono apartado no entran.",
    "stats.025" to "CUÁNDO VA MEJOR",
    "stats.026" to "Recuerdas mejor alrededor de las ",
    "stats.027" to ". No es una orden de estudiar justo entonces: a esa hora te cuesta menos y conviene poner el recordatorio una hora antes.",
    "stats.028" to "Aún es pronto para señalar una hora: hacen falta al menos 12 repasos dentro de la misma hora. Las barras pálidas todavía tienen pocos datos.",
    "stats.029" to "NO SE QUEDA",
    "stats.030" to "Ninguna por ahora: nada se ha olvidado cuatro veces o más.",
    "stats.031" to "A la derecha, cuántas veces se olvidó la frase. Habla de la frase, no de ti.",
    "stats.032" to "HOY",
    "set.001" to "No se pudo abrir el archivo",
    "set.002" to "No se pudo abrir el archivo",
    "set.003" to "Fuente aplicada: ",
    "set.004" to "Sin permiso para notificaciones no llegará el recordatorio",
    "set.005" to "El archivo de ajustes está dañado",
    "set.006" to "Ajustes restaurados",
    "set.007" to "Ajustes restaurados. La fuente «",
    "set.008" to "» debe elegirse de nuevo: el archivo de fuente es tuyo y no se incluye en la copia de seguridad.",
    "set.009" to "Respuestas añadidas: ",
    "set.010" to " · recalculadas ",
    "set.011" to " · omitidas ",
    "set.012" to "Ajustes",
    "set.013" to "Carga",
    "set.015" to "AUTO",
    "set.016" to "MANUAL",
    "set.017" to "AHORA · ",
    "set.018" to "TARJETAS AL DÍA",
    "set.019" to "Aspecto",
    "set.020" to "Animaciones",
    "set.022" to "Vibración",
    "set.024" to "Idioma",
    "set.026" to "Voz",
    "set.027" to "Habla el motor que ya está en el teléfono. No se descarga nada ni sale nada a la red.",
    "set.028" to "Leer en voz alta",
    "set.029" to "El icono de sonido solo aparece donde no revela la respuesta",
    "set.030" to "comprobando lo que hay en el teléfono…",
    "set.031" to "No hay motor de voz en el teléfono. Sirve cualquiera sin conexión, como RHVoice o SherpaTTS de F-Droid. Vuelve después de instalarlo.",
    "set.032" to "AJUSTES DEL MOTOR DE VOZ",
    "set.033" to "No se encontró esa sección en los ajustes del teléfono",
    "set.034" to "Hay un motor, pero no tiene voces sin conexión para estos idiomas. Hay que descargarlas una vez; después funcionan sin red.",
    "set.035" to "INSTALAR VOCES",
    "set.036" to "El motor no puede descargar voces por sí solo; mira sus propios ajustes",
    "set.037" to "no hay voces sin conexión para este idioma",
    "set.038" to "PREDETERMINADA",
    "set.039" to "El primer sonido tras abrir la app puede tardar un segundo: el motor despierta.",
    "set.040" to "Fuente",
    "set.041" to "Tu propio .ttf u .otf para el texto de las tarjetas. El archivo se comprueba antes de aplicarlo.",
    "set.042" to "AHORA · SISTEMA",
    "set.043" to "AHORA · ",
    "set.044" to "ELEGIR ARCHIVO",
    "set.045" to "RESTABLECER",
    "set.046" to "Se restauró la fuente del sistema",
    "set.047" to "Recordatorio",
    "set.049" to "Recordarme",
    "set.050" to "a las ",
    "set.051" to "desactivado",
    "set.052" to "Datos",
    "set.053" to "El registro de respuestas es lo único que no puede reconstruirse. Todo lo demás se vuelve a calcular a partir de él.",
    "set.054" to "Exportar automáticamente una vez por semana",
    "set.055" to "En la carpeta Documents/ikna",
    "set.056" to "EXPORTAR",
    "set.057" to "No se pudo guardar el archivo",
    "set.058" to "Ajustes guardados. El registro aún está vacío; no hay nada que exportar.",
    "set.059" to "Registro y ajustes guardados en Documents/ikna",
    "set.060" to "RESTAURAR",
    "set.063" to "Poco frecuente",
    "set.065" to "OCULTAR",
    "set.066" to "MOSTRAR",
    "set.067" to "RECONSTRUIR LA CAPA DE PALABRAS",
    "set.068" to "Capa de palabras reconstruida desde el registro",
    "set.069" to "PANTALLA TÉCNICA",
    "set.070" to "EMPEZAR DE NUEVO",
    "set.071" to "Borrar todo",
    "set.072" to "Se borran tarjetas, fechas, estadísticas, ajustes y el registro de respuestas. El registro se exporta antes a Documents/ikna.",
    "set.073" to "BORRAR TODO DE VERDAD",
    "set.074" to "BORRAR LOS DATOS",
    "set.075" to "Pulsa otra vez si realmente quieres hacerlo. No se puede deshacer.",
    "set.076" to "la segunda pulsación borra de inmediato",
    "set.077" to "hay que pulsar dos veces",
    "set.078" to "¿Empezar de nuevo?",
    "set.079" to "Se pondrán a cero las fechas, las estadísticas y la capa de palabras. El registro de respuestas permanece y permite recuperarlo todo con «Restaurar».",
    "set.080" to "EMPEZAR DE NUEVO",
    "set.081" to "Estadísticas puestas a cero",
    "set.082" to "CANCELAR",
    "set.083" to "FONDO",
    "set.084" to "TEXTO",
    "set.085" to "ATENUADO",
    "set.086" to "ACENTO",
    "set.087" to "CONTRASTE · TEXTO ",
    "set.088" to " · ATENUADO ",
    "set.089" to " · ACENTO ",
    "set.090" to "algo se lee mal sobre su propio fondo; el color se aplica de todos modos",
    "set.091" to "CARGA",
    "set.092" to "ASPECTO",
    "set.093" to "IDIOMA",
    "set.094" to "VOZ",
    "set.095" to "FUENTE",
    "set.096" to "RECORDATORIO",
    "set.097" to "DATOS",
    "set.098" to "POCO FRECUENTE",
    "set.099" to "SISTEMA",
    "set.100" to "РУССКИЙ",
    "set.101" to "OSCURO",
    "set.102" to "CLARO",
    "set.103" to "PROPIO",
    "set.104" to "POLACO",
    "set.105" to "RUSO",
    "set.106" to "INGLÉS",
    "set.107" to "ALEMÁN",
    "set.108" to "ESPAÑOL",
    "set.109" to "FRANCÉS",
    "set.110" to "fuente",
    "set.114" to "PALETA",
    "set.116" to "BRASA",
    "set.117" to "BIBLIOTECA",
    "set.118" to "TINTA",
    "set.119" to "CIRUELA",
    "set.120" to "CERO",
    "set.121" to "NEUTRAL",
    "set.125" to "ROSA",
    "set.126" to "ESCARCHA",
    "set.127" to "FÓSFORO",
    "set.141" to "ULTRAVIOLETA",
    "set.142" to "LAGUNA",
    "set.143" to "COBALTO",
    "set.122" to "ILUMINACIÓN",
    "set.128" to "TODOS LOS IDIOMAS",
    "set.130" to "Voz del teléfono",
    "set.131" to "Lee los idiomas que no cubre ninguno de tus modelos",
    "set.132" to "Hablar siempre",
    "set.133" to "La tarjeta se lee cada vez que aparece",
    "set.134" to "La tarjeta solo se lee en el primer encuentro",
    "set.135" to "Tarjetas retiradas de la rotación: ",
    "set.136" to "Volver a incluirlas",
    "set.137" to "Las tarjetas han vuelto",
    "set.138" to "Actualizaciones",
    "set.139" to "La app se instala desde un archivo, así que solo ella puede avisarte de que existe una versión nueva.",
    "set.140" to "ACTUALIZACIÓN",
    "set.123" to "BETA",
    "set.124" to "En beta y desactivado de forma predeterminada: el motor del teléfono decide cómo suena la voz, y una mala voz es peor que el silencio.",
    "dbg.001" to "← ATRÁS",
    "dbg.002" to "EXPORTAR EL REGISTRO DE RESPUESTAS",
    "dbg.003" to "Archivo: Documents/ikna/",
    "dbg.004" to "No se pudo guardar el archivo",
    "dbg.005" to "RECONSTRUIR LA CAPA DE PALABRAS",
    "dbg.006" to "Capa de palabras reconstruida",
    "dbg.007" to "RECONSTRUIR EL PLAN DE HOY",
    "dbg.008" to "Plan de hoy reconstruido",
    "dbg.009" to "Decisiones del regulador por día",
    "dbg.010" to " nuevos=",
    "dbg.011" to " pendientes=",
    "dbg.012" to " previsión3d=",
    "dbg.013" to " atraso=",
    "dbg.014" to " precisión=",
    "dbg.015" to " margen=",
    "deck.001" to "No se pudo leer ni una línea",
    "deck.002" to "Fragmentos añadidos: ",
    "deck.003" to ", omitidos ",
    "deck.004" to "Mazos",
    "deck.005" to "Aún no hay mazos. El signo más de abajo contiene el prompt para la IA y un lugar donde pegarlo.",
    "deck.006" to "leyendo el archivo…",
    "deck.007" to "HOY",
    "deck.008" to "nada pendiente",
    "deck.009" to "hoy ",
    "deck.010" to "nada para hoy",
    "deck.014" to "tarjetas",
    "deck.015" to "tarjeta",
    "deck.016" to "tarjetas",
    "deck.017" to "tarjetas",
    "deck.018" to " · <1 min",
    "deck.019" to " min",
    "add.001" to "Mazo nuevo",
    "add.002" to "Un mazo es texto plano. Cada línea es una tarjeta: una frase, una oración que la contiene y la traducción, separadas por |.",
    "add.003" to "Copia el prompt y envíalo a cualquier IA.",
    "add.004" to "Indica el idioma y el tema: «polaco, cocina, 100 tarjetas».",
    "add.005" to "Copia la respuesta completa o guárdala como archivo.",
    "add.006" to "Vuelve aquí y pega el texto, o elige el archivo.",
    "add.007" to "Copiar el prompt",
    "add.008" to "Guardar el prompt en un archivo",
    "add.009" to "Prompt copiado",
    "add.010" to "Prompt guardado",
    "add.011" to "No se pudo guardar el prompt",
    "add.012" to "Pega aquí las líneas del mazo",
    "add.013" to "Pegar un ejemplo",
    "add.014" to "Añadir desde texto",
    "add.015" to "Elegir un archivo",
    "add.016" to "FRASE | ORACIÓN QUE LA CONTIENE | TRADUCCIÓN",
    "add.017" to "leyendo…",
    "add.018" to "El archivo es demasiado grande para un mazo",
    "add.019" to "No se pudo leer el archivo",
    "add.020" to "Pega primero el texto",
    "add.021" to "Tarjetas añadidas: ",
    "add.022" to ", líneas omitidas: ",
    "add.023" to "Línea ",
    "add.024" to " — ",
    "add.025" to "No se pudo usar ninguna línea",
    "add.026" to "Hecho",
    "add.027" to "acostumbrarse a|Se tarda un tiempo en acostumbrarse al ruido.|habituarse\\nvigilar|¿Puedes vigilar mi bolso?|mantener a la vista",
    "add.028" to "Ejemplo pegado",
    "add.029" to "Borrar",
    "add.030" to "Mi mazo",
    "add.031" to "la línea no tiene tres partes",
    "add.032" to "un campo está vacío",
    "add.033" to "la frase no aparece en la oración",
    "add.034" to "la línea es demasiado larga",
    "add.035" to "esa frase ya se usó",
    "share.001" to "compartir",
    "share.002" to "Enviar mazo",
    "share.003" to "no se pudo compartir",
    "share.004" to "este mazo todavía no tiene nada que enviar",
    "dp.001" to "En uso",
    "dp.002" to "Desactivado",
    "dp.003" to "Idioma del mazo",
    "dp.004" to "Se usa para la voz. Un mazo importado toma su idioma de las tarjetas; aquí se corrige.",
    "dp.005" to "sin voz",
    "dp.006" to "Enviar mazo",
    "dp.007" to "Eliminar mazo",
    "dp.008" to "Pulsa otra vez si realmente quieres hacerlo",
    "dp.009" to "Se eliminan las tarjetas del mazo y su planificación. Las respuestas permanecen en las estadísticas: ese registro nunca se reescribe.",
    "dp.010" to "Añadir tarjetas",
    "dp.011" to "Añadiendo…",
    "dp.013" to "Nombre del mazo",
    "dp.014" to "Pronunciación",
    "dp.015" to "Cómo suena la frase. La grafía inglesa la entiende casi cualquiera; el AFI es exacto.",
    "dp.016" to "Inglesa",
    "dp.017" to "AFI",
    "dp.018" to "Desactivada",
    "dp.019" to "No se muestra nada",
    "add.036" to "cómo funciona",
    "add.037" to "ocultar",
    "add.038" to "En qué idioma están las tarjetas",
    "add.039" to "Solo se usa para la voz. Se puede cambiar después en la página del mazo.",
    "add.040" to "Qué pedirle al modelo",
    "add.041" to "Cuántas tarjetas",
    "add.042" to "Idioma de los significados",
    "add.043" to "principiante",
    "add.044" to "puede mantener una conversación",
    "add.045" to "fluido",
    "add.046" to "Nivel",
    "add.047" to "Tema o situación",
    "add.048" to "por ejemplo, cafeterías y pedir comida",
    "add.049" to "Las respuestas entran en el propio prompt, así que no queda nada que escribir en el chat.",
    "add.050" to "Conviene revisar estas líneas: ",
    "add.051" to "el significado repite el propio término",
    "add.052" to "una formulación imprecisa",
    "add.053" to "este significado ya apareció antes",
    "add.054" to "contiene números; compáralos con la fuente",
    "add.055" to "Qué se está aprendiendo",
    "add.056" to "un idioma",
    "add.057" to "una materia",
    "add.058" to "Un mazo de una materia no se lee en voz alta ni pide hablar: solo reconocer y recordar.",
    "add.059" to "algunos conocimientos previos",
    "add.060" to "Materia y sección",
    "add.061" to "por ejemplo, neurociencia, plasticidad sináptica",
    "add.062" to "Idioma de las tarjetas",
    "add.063" to "Pegar desde el portapapeles",
    "add.064" to "El portapapeles no contiene texto",
    "add.065" to "líneas",
    "add.066" to "caracteres",
    "add.067" to "MOSTRAR EL TEXTO",
    "add.068" to "OCULTAR EL TEXTO",
    "add.069" to "y más líneas: ",
    "add.070" to "los saltos de línea se perdieron al pegar y esta línea no pudo reconstruirse. Pulsa «Pegar desde el portapapeles»: el teclado recorta los textos grandes",
    "add.071" to "El texto superaba el límite y se recortó. Divide el mazo en dos.",
    "add.072" to "Si no hay un mazo preparado",
    "add.073" to "La vía opcional: pedir un mazo a un modelo. Lo que llegue hay que revisarlo con la vista.",
    "add.074" to "MÉTODO CON MODELO",
    "card.002" to "toca en cualquier lugar",
    "card.003" to "← NO LO SÉ",
    "card.004" to "LO SÉ →",
    "sess.001" to "un momento…",
    "sess.003" to "MÍNIMO COMPLETADO",
    "sess.004" to "Mazo terminado",
    "sess.005" to "Eso es todo por hoy",
    "sess.006" to "No hay tarjetas hoy",
    "sess.007" to "No queda nada por repasar; lo demás aún no vence",
    "sess.008" to "COMPROBAR DE NUEVO",
    "sess.009" to "UN POCO MÁS +5",
    "sess.010" to "solo repasos; no salen fragmentos nuevos de aquí",
    "sess.011" to "esta respuesta ya no puede deshacerse",
    "sess.012" to "respuesta registrada",
    "sess.013" to "DESHACER",
    "sess.014" to "ACEPTAR",
    "sess.015" to "reconocer",
    "sess.016" to "completar",
    "sess.017" to "decirlo en voz alta",
    "sess.018" to "El plan del día está cerrado. Los fragmentos nuevos llegarán solos mañana.",
    "sess.019" to "Primer día: empezamos con muy poco.",
    "sess.020" to "Todo está repasado; las siguientes aún no vencen.",
    "sess.021" to "Ya hay muchos repasos por delante; las palabras nuevas esperarán.",
    "sess.022" to "Hoy solo los repasos más útiles; lo nuevo volverá cuando haya espacio.",
    "sess.023" to "Qué bueno verte de nuevo. Empezaremos con un paso breve y familiar.",
    "sess.024" to "Una semana tranquila: lo nuevo puede esperar; las fechas ya se han adaptado.",
    "sess.025" to "Es demasiado tarde para fragmentos nuevos; los veremos por la mañana. Los repasos permanecen.",
    "sess.026" to "Hasta que se asiente lo antiguo, nada nuevo.",
    "sess.027" to "Qué bueno verte de nuevo. El plan ya se adaptó a tu ritmo. Hoy hay un paso breve y finito. Continúa desde donde estás.",
    "sess.028" to "Añadiré al menos un fragmento nuevo para que no nos detengamos.",
    "sess.029" to "Ya no quedan fragmentos nuevos aquí: todos son conocidos. Los repasos seguirán llegando en sus fechas; para material nuevo hace falta otro mazo.",
    "sess.030" to "siguiente: hoy a las ",
    "sess.031" to "siguiente: mañana a las ",
    "sess.032" to "siguiente: dentro de ",
    "sess.033" to "días",
    "sess.034" to "día",
    "sess.035" to "días",
    "sess.036" to "días",
    "sess.037" to " · <1 MIN",
    "sess.038" to " MIN",
    "sess.039" to "tarjetas",
    "sess.040" to "tarjeta",
    "sess.041" to "tarjetas",
    "sess.042" to "tarjetas",
    "sess.043" to "Ayer fue largo; hoy será más ligero y sin nada nuevo.",
    "sess.044" to "MARCAR COMO INCORRECTA",
    "sess.045" to "Retirada de la rotación. El error no se añadió a tus estadísticas.",
    "sess.046" to "el término",
    "sess.047" to "de memoria",
    "onb.001" to "En frases, no en palabras",
    "onb.002" to "Dentro hay fragmentos preparados: trozos breves y vivos del habla. Los nuevos se añaden solos; no hay que escribir nada a mano.",
    "onb.003" to "Saltarse un día no es fallar",
    "onb.004" to "Una semana perdida no deja montón: lo viejo vuelve poco a poco.",
    "onb.005" to "El mínimo es una tarjeta",
    "onb.006" to "Una tarjeta cierra todo el día. Si quieres más, existe «un poco más» y no hará más pesado el día siguiente.",
    "onb.007" to "PREPARANDO TARJETAS…",
    "onb.008" to "SIGUIENTE",
    "onb.009" to "EMPEZAR",
    "onb.010" to "SALTAR",
    "onb.011" to "Izquierda y derecha",
    "onb.012" to "Izquierda si no la sabes, derecha si sí. La respuesta se puede deshacer justo después.",
    "speaker.001" to "EXCELENTE",
    "speaker.002" to "BUENO",
    "speaker.003" to "NORMAL",
    "speaker.004" to "BAJO",
    "remind.001" to "Una tarjeta",
    "remind.002" to "Una basta para cerrar el día",
    "a11y.001" to "Atrás",
    "a11y.002" to "Ajustes",
    "a11y.003" to "Estadísticas",
    "a11y.004" to "Añadir un mazo",
    "a11y.005" to "Leer en voz alta",
    "a11y.006" to "Mazo en uso",
    "a11y.007" to "Explicar este número",
    "a11y.008" to "No lo sé",
    "a11y.009" to "Lo sé",
    "a11y.010" to "Ajustes del mazo",
    "voice.001" to "Voz",
    "voice.002" to "Leyendo ahora",
    "voice.003" to "Voz propia del teléfono",
    "voice.004" to "Esta compilación no incluye motor de modelos; solo lee la voz del teléfono",
    "voice.005" to "Hay un modelo instalado, pero no se cargó. Lee la voz del teléfono",
    "voice.006" to "Sin modelo. Lee la voz del teléfono",
    "voice.007" to "Comprobando el modelo…",
    "voice.008" to "El modelo está cargado y listo",
    "voice.010" to "Probar la voz",
    "voice.011" to "Tus modelos",
    "voice.012" to "Tú aportas el modelo: una carpeta Kokoro o Piper del teléfono. No se descarga nada; la app no usa internet.",
    "voice.013" to "Eliminar el modelo",
    "voice.014" to "Idioma del modelo",
    "voice.015" to "Cualquiera",
    "voice.016" to "Esta compilación no tiene motor. Tu modelo no funcionará aquí; usa la compilación marcada voice.",
    "voice.017" to "Añadir otro modelo",
    "voice.018" to "Archivos copiados: ",
    "voice.019" to "No parece un modelo: no hay ningún archivo .onnx en la carpeta",
    "voice.020" to "La carpeta elegida está un nivel demasiado arriba. Ábrela y elige la carpeta que contiene el modelo",
    "voice.021" to "Hay varios modelos en una carpeta. Deja solo uno",
    "voice.022" to "Falta tokens.txt. Usa la compilación sherpa-onnx del modelo, no los archivos Piper originales",
    "voice.023" to "No se pudo copiar: ",
    "voice.024" to "Modelo añadido",
    "voice.025" to "La lectura está desactivada; el interruptor superior la activa",
    "voice.026" to "Los modelos están en la página de versiones de sherpa-onnx, dentro de tts-models. Kokoro habla inglés; Piper cubre casi cualquier idioma, incluidos ruso y polaco.",
    "voice.027" to "Falta voices.bin. La descarga de Kokoro terminó antes de tiempo",
    "voice.028" to "No hay con qué pronunciar: falta espeak-ng-data y tampoco hay léxico",
    "voice.029" to "Añadir un modelo",
    "voice.030" to "Leer las tarjetas en voz alta",
    "voice.031" to "Mientras esté desactivado, las tarjetas permanecen en silencio, haya o no modelo",
    "voice.032" to "Quién lee cada mazo",
    "voice.033" to "lo lee el modelo",
    "voice.034" to "lo lee la voz del teléfono",
    "voice.035" to "nadie: el modelo no conoce este idioma y el teléfono no tiene voz para él",
    "voice.036" to "Un modelo habla un idioma. El idioma del mazo sale de sus tarjetas y se cambia en su página.",
    "voice.037" to "SIN IDIOMA",
    "voice.038" to "desactivado",
    "voice.039" to "Número de voz",
    "voice.040" to "Un modelo habla cada idioma",
    "voice.041" to "Añadir un archivo .tar.bz2",
    "voice.042" to "No es un archivo de modelo",
    "voice.043" to "No hay espacio suficiente: un modelo descomprimido ocupa unas tres veces el archivo",
    "voice.044" to "La app descomprime el archivo por sí misma",
    "voice.045" to "Idioma leído del nombre del modelo:",
    "voice.046" to "OTRO IDIOMA",
    "voice.047" to "Solo el propio modelo sabe cuántas voces tiene: pulsa la prueba y el número aparecerá aquí.",
    "voice.048" to "Velocidad",
    "voice.049" to "Descomprimiendo:",
    "voice.050" to "Un modelo grande tarda minutos en descomprimirse: el procesador del teléfono deshace bzip2.",
    "voice.051" to "Puedes salir de esta pantalla; la instalación continúa. No dejes la app en segundo plano durante mucho tiempo.",
    "look.001" to "Apariencia",
    "look.002" to "Las letras y el color del cuadrado en la lista de mazos. Solo tuyos: quien reciba el mazo obtiene las tarjetas y nada más.",
    "look.003" to "Color del cuadrado",
    "look.004" to "Uno o dos caracteres. Si se deja vacío, el cuadrado los calcula solo.",
    "bar.001" to "La marca ikna",
    "bar.003" to "Para la mano izquierda",
    "upd.001" to "ACTUALIZACIÓN DISPONIBLE",
    "upd.002" to "Tamaño: ",
    "upd.003" to "MB",
    "upd.004" to "Novedades:",
    "upd.005" to "ACTUALIZAR",
    "upd.006" to "SALTAR",
    "upd.007" to "La app descarga el archivo; aquí aparecen la barra y el porcentaje. El instalador de Android coloca la nueva versión sobre la antigua y conserva tarjetas y progreso.",
    "upd.008" to "Buscar actualizaciones",
    "upd.009" to "Una petición a la página de versiones, como máximo una vez al día. No se envía nada. Si se desactiva, no se abre ninguna conexión.",
    "upd.010" to "COMPROBAR AHORA",
    "upd.011" to "Instalada: ",
    "upd.012" to "No hay nada más nuevo. Si no hay red, la comprobación simplemente falló; la app no puede distinguir ambos casos.",
    "upd.013" to "PÁGINA DE VERSIONES",
    "upd.014" to "COMPROBANDO…",
    "upd.015" to "Omitida: ",
    "upd.016" to "Actualizar a ",
    "upd.017" to "DESCARGANDO",
    "upd.018" to "El archivo ya está aquí. El instalador de Android coloca la nueva versión sobre la antigua; se conservan tarjetas, progreso y ajustes.",
    "upd.019" to "CANCELAR",
    "upd.020" to "INSTALAR",
    "upd.021" to "Android pide permiso para instalar apps desde esta fuente. Sin él no se abrirá el instalador. El archivo ya está descargado y permanece guardado.",
    "upd.022" to "PERMITIR",
    "upd.023" to "La descarga falló: se cortó la conexión o el archivo llegó incompleto. Reintenta o descárgalo en el navegador.",
    "upd.024" to "REINTENTAR",
    "upd.025" to "EN EL NAVEGADOR",
    "cat.001" to "Catálogo de mazos",
    "cat.002" to "Las frases vienen de Tatoeba; las formas de las palabras, de Wiktionary. La licencia y el crédito se muestran antes de descargar.",
    "cat.003" to "CARGANDO LA LISTA…",
    "cat.004" to "La lista no llegó: no hay red o la página del catálogo no responde. Nada se rompió: el mazo incluido y la creación mediante un modelo siguen disponibles.",
    "cat.005" to "PÁGINA DEL CATÁLOGO",
    "cat.006" to "REINTENTAR",
    "cat.007" to "Qué aprender",
    "cat.008" to "Significados en",
    "cat.009" to "Tema",
    "cat.010" to "Nivel",
    "cat.011" to "TODOS",
    "cat.012" to "Este par está bien cubierto: el corpus contiene muchas oraciones y los mazos son grandes.",
    "cat.013" to "Este par tiene poco material: el corpus contiene pocas oraciones y los mazos son más cortos. Es un límite de la fuente, no de la app.",
    "cat.014" to "Todavía no hay nada para este par. El README del proyecto muestra la cobertura de cada par.",
    "cat.015" to "tarjetas",
    "cat.016" to "Licencia: ",
    "cat.017" to "Fuente: ",
    "cat.018" to "DESCARGAR",
    "cat.019" to "DESCARGANDO",
    "cat.020" to "La descarga falló: se cortó la conexión o el archivo llegó incompleto. No se instaló nada; puedes reintentarlo.",
    "cat.021" to "El archivo llegó, pero no se pudo crear ni una tarjeta. No se añadió ningún mazo.",
    "cat.022" to "Hecho. Tarjetas en el mazo: ",
    "cat.023" to "CONSTRUYENDO EL MAZO…",
    "cat.024" to "MB",
    "cat.025" to "CC BY-SA: un mazo derivado de este y compartido conserva la misma licencia. Estudiarlo no obliga a nada.",
    "cat.026" to "Lista creada: ",
    "cat.027" to "principiante",
    "cat.028" to "intermedio",
    "cat.029" to "avanzado",
    "cat.030" to "Nada coincide con estos filtros.",
    "cat.031" to "Un mazo preparado",
    "cat.032" to "Si hablar con un modelo no merece la pena: un mazo del catálogo, oraciones escritas por personas, licencia abierta y autoría indicada.",
    "cat.033" to "ABRIR EL CATÁLOGO",
    "cat.034" to "YA DESCARGADO",
    "cat.035" to "descargar de nuevo",
    "cat.036" to "MOSTRAR EJEMPLOS",
    "cat.037" to "CARGANDO EJEMPLOS…",
    "cat.038" to "REINTENTAR EJEMPLOS",
    "cat.039" to "EJEMPLOS DEL MAZO",
    "cat.040" to "TARJETA ",
    "cat.041" to "Con pronunciación",
    "a11y.011" to "Buscar mazos",
    "src.001" to "Fuente · ",
    "src.002" to "¿Esta tarjeta es incorrecta?",
    "src.003" to "La tarjeta se ocultará y se copiará un informe listo para pegar con su texto y el enlace a la fuente. Puedes pegarlo en GitHub Issues.",
    "src.004" to "OCULTAR Y COPIAR",
    "src.005" to "CANCELAR",
    "src.006" to "Tarjeta oculta · informe copiado",
    "src.007" to "FUENTE",
    "search.001" to "Buscar mazos",
    "search.002" to "Solo busca en los mazos ya instalados en este teléfono. No usa la red.",
    "search.003" to "Frase, oración o traducción",
    "search.004" to "BUSCAR",
    "search.005" to "BUSCANDO…",
    "search.006" to "Escribe al menos dos caracteres.",
    "search.007" to "No se encontró nada en los mazos instalados.",
    "search.008" to "Se muestran las primeras 80 coincidencias; concreta la búsqueda para reducir la lista.",
    "search.009" to "La búsqueda no terminó. No se modificó ningún dato; puedes reintentarlo.",
    "search.010" to "MAZO · ",
    "mig.001" to "Actualizando la planificación",
    "mig.002" to "Los mazos y el historial permanecen. Las respuestas se reproducen una vez con FSRS-6.",
    "mig.003" to "La planificación no se actualizó",
    "mig.004" to "No se eliminó nada: los mazos y el historial siguen aquí. Puedes repetir el recálculo sin riesgo.",
    "mig.005" to "REINTENTAR",
    "diag.001" to "Diagnóstico",
    "diag.002" to "Solo un resumen técnico: sin nombres de mazos, texto de tarjetas ni historial. No se envía nada.",
    "diag.003" to "MOSTRAR DIAGNÓSTICO",
    "diag.004" to "OCULTAR DIAGNÓSTICO",
    "diag.005" to "RECOPILANDO…",
    "diag.006" to "COPIAR EL RESUMEN",
    "diag.007" to "Diagnóstico copiado",
    "diag.008" to "No se pudo recopilar el diagnóstico",

    "anki.001" to "Desde Anki",
    "anki.002" to "Elige un archivo .apkg. Todo se queda en este teléfono.",
    "anki.003" to "Sirve cualquier .apkg de Anki, antiguo o nuevo.",
    "anki.005" to "ELEGIR .APKG",
    "anki.006" to "LEYENDO EL ARCHIVO…",
    "anki.007" to "Puedes salir de esta pantalla; la importación continúa.",
    "anki.008" to "Mazos: ",
    "anki.009" to "Tarjetas: ",
    "anki.010" to "Eventos de repaso añadidos: ",
    "anki.011" to "Registros de historial omitidos: ",
    "anki.012" to "Suspendidas o enterradas en Anki, no añadidas: ",
    "anki.013" to "Tarjetas omitidas: ",
    "anki.014" to "Con imágenes o sonido: ",
    "anki.015" to "El historial es muy grande: se usaron las 100 000 valoraciones más recientes.",
    "anki.016" to "LISTO",
    "anki.017" to "IMPORTAR OTRO",
    "anki.018" to "No se pudo leer este .apkg.",
    "anki.019" to "El paquete no contiene una colección de Anki.",
    "anki.020" to "No se pudo leer esta colección. No se cambió nada.",
    "anki.021" to "El archivo está dañado o su formato aún no se puede leer.",
    "anki.022" to "El paquete supera el límite seguro de 300 MB. No cambió ningún dato.",
    "anki.023" to "El paquete no contiene tarjetas de texto legibles. No cambió ningún dato.",
    "anki.024" to "Nada cambió: corrige la exportación e inténtalo de nuevo.",
    "anki.025" to "Qué se trajo",
    "anki.026" to "Trae un .apkg desde el teléfono: mazos e historial sin reconstruirlos a mano.",
    "anki.027" to "IMPORTAR DESDE ANKI",
    "anki.028" to "Aquí el calendario se construye de nuevo; los intervalos de Anki no se trasladan.",
    "anki.029" to "El archivo original de Anki no se toca.",
    "anki.030" to "Recuperadas de los campos: ",
    "anki.031" to "El archivo solo contiene la tarjeta de aviso de Anki. Vuelve a exportarlo.",
    "anki.032" to "Idiomas: ",
    "anki.033" to "materia",
    "anki.034" to "sin determinar",
)
