package dev.ikna.ui.text

val STRINGS_FR: Map<String, String> = mapOf(
    "app.001" to "Rappel", "app.002" to "Un rappel par jour, seulement si le minimum n’est pas encore fait",
    "font.001" to "Impossible de lire le fichier", "font.002" to "Ce fichier est trop volumineux pour une police",
    "font.003" to "Impossible d’enregistrer la police", "font.004" to "Impossible d’enregistrer la police",
    "font.005" to "Ce fichier n’est pas une police", "font.006" to "C’est une collection .ttc ; il faut une seule police .ttf ou .otf",
    "font.007" to "C’est une police web .woff ; Android ne peut pas la lire, utilisez .ttf ou .otf",
    "font.008" to "Ce fichier n’est pas une police", "font.009" to "Le fichier de police est endommagé",
    "font.010" to "Le fichier de police est tronqué", "font.011" to "Le fichier de police est tronqué",
    "font.012" to "La police n’a pas de table de caractères", "font.013" to "La police ne contient aucune lettre",
    "deckrepo.001" to "Votre propre paquet", "stats.001" to "Statistiques", "stats.002" to "30 DERNIERS JOURS",
    "stats.003" to "Chaque marque est un jour étudié, aujourd’hui à droite. Sauter un jour ne remet rien à zéro : il n’y a aucune série à briser.",
    "stats.004" to "NORME QUOTIDIENNE", "stats.005" to "Cartes par jour, calculées sur vos jours récents et recalculées automatiquement.",
    "stats.006" to "Une estimation de départ, pas une mesure. Votre valeur sera calculée après au moins trois jours de sessions.",
    "stats.007" to "MOTS EN MÉMOIRE", "stats.008" to "RÉPONDUES AUJOURD’HUI",
    "stats.009" to "Les mots sont comptés séparément des fragments : un mot revient dans plusieurs phrases et tient mieux que chacune d’elles.",
    "stats.010" to "À REVOIR SOUS 14 JOURS", "stats.011" to "Nombre de cartes arrivant à échéance. Si une montagne se forme, aucun nouveau fragment ne sera ajouté ces jours-là.",
    "stats.012" to "RÉTENTION", "stats.013" to "Il faut au moins 20 révisions pour obtenir une mesure. Pour l’instant : ",
    "stats.014" to "Sur ", "stats.015" to " révisions ce mois-ci, rappelées : ",
    "stats.016" to " %. Seules les révisions comptent : une première rencontre ne peut pas être oubliée.",
    "stats.017" to "Le planning vise environ 90 %. Sous 80 %, les intervalles sont trop longs. La charge s’ajuste, mais si cela dure, réduisez la norme.",
    "stats.018" to "Le planning vise environ 90 %. Au-dessus de 95 %, vous révisez plus que nécessaire : des intervalles plus longs suffiraient.",
    "stats.019" to "Le planning vise environ 90 % et vous êtes dans cette zone. Rien à changer.",
    "stats.020" to "MINUTES AUJOURD’HUI", "stats.021" to "CETTE SEMAINE",
    "stats.022" to "Seul le temps avec une carte à l’écran compte. Une carte vous prend environ ", "stats.023" to " s.",
    "stats.024" to "Seul le temps avec une carte à l’écran compte ; les pauses téléphone posé sont exclues.",
    "stats.025" to "MEILLEUR MOMENT", "stats.026" to "Le rappel fonctionne le mieux vers ",
    "stats.027" to ". Ce n’est pas une obligation : cette heure vous coûte simplement moins, et un rappel une heure avant est logique.",
    "stats.028" to "Trop tôt pour choisir une heure : il faut au moins 12 révisions dans une même heure. Les barres pâles manquent encore de données.",
    "stats.029" to "NE TIENT PAS", "stats.030" to "Aucune pour l’instant : rien n’a été oublié quatre fois ou plus.",
    "stats.031" to "À droite : combien de fois la phrase a été oubliée. Cela concerne la phrase, pas vous.",
    "stats.032" to "AUJOURD’HUI",
    "set.001" to "Impossible d’ouvrir le fichier", "set.002" to "Impossible d’ouvrir le fichier", "set.003" to "Police appliquée : ",
    "set.004" to "Sans autorisation de notification, le rappel n’arrivera pas", "set.005" to "Le fichier de réglages est endommagé",
    "set.006" to "Réglages restaurés", "set.007" to "Réglages restaurés. La police «",
    "set.008" to "» doit être choisie à nouveau : votre fichier de police n’est pas inclus dans la sauvegarde.",
    "set.009" to "Réponses ajoutées : ", "set.010" to " · recalculées ", "set.011" to " · ignorées ",
    "set.012" to "Réglages", "set.013" to "Charge", "set.015" to "AUTO", "set.016" to "MANUEL",
    "set.017" to "MAINTENANT · ", "set.018" to "CARTES PAR JOUR", "set.019" to "Apparence",
    "set.020" to "Animations", "set.022" to "Vibration", "set.024" to "Langue", "set.026" to "Voix",
    "set.027" to "C'est le moteur déjà installé sur le téléphone qui parle. Rien n'est téléchargé, rien ne part sur le réseau.",
    "set.028" to "Lire à voix haute", "set.029" to "L’icône sonore n’apparaît que lorsqu’elle ne révèle pas la réponse",
    "set.030" to "vérification des voix du téléphone…",
    "set.031" to "Aucun moteur vocal sur le téléphone. Installez un moteur hors ligne, par exemple RHVoice ou SherpaTTS depuis F-Droid, puis revenez.",
    "set.032" to "RÉGLAGES DU MOTEUR VOCAL", "set.033" to "Cette section des réglages du téléphone est introuvable",
    "set.034" to "Le moteur existe, mais sans voix hors ligne pour ces langues. Téléchargez-les une fois ; elles fonctionneront ensuite sans réseau.",
    "set.035" to "INSTALLER DES VOIX", "set.036" to "Le moteur ne sait pas télécharger les voix ; consultez ses réglages",
    "set.037" to "aucune voix hors ligne pour cette langue", "set.038" to "PAR DÉFAUT",
    "set.039" to "Le premier son après le lancement peut prendre une seconde : le moteur se réveille.",
    "set.040" to "Police", "set.041" to "Votre .ttf ou .otf pour le texte des cartes. Le fichier est vérifié avant d'être appliqué.",
    "set.042" to "MAINTENANT · SYSTÈME", "set.043" to "MAINTENANT · ", "set.044" to "CHOISIR UN FICHIER",
    "set.045" to "RÉINITIALISER", "set.046" to "Police système restaurée", "set.047" to "Rappel",
    "set.049" to "Me rappeler", "set.050" to "à ", "set.051" to "désactivé", "set.052" to "Données",
    "set.053" to "Le journal des réponses est la seule chose impossible à reconstruire. Tout le reste est recalculé depuis celui-ci.",
    "set.054" to "Exporter automatiquement chaque semaine", "set.055" to "Dans le dossier Documents/ikna",
    "set.056" to "EXPORTER", "set.057" to "Impossible d’enregistrer le fichier",
    "set.058" to "Réglages enregistrés. Le journal est encore vide : rien à exporter.",
    "set.059" to "Journal et réglages enregistrés dans Documents/ikna", "set.060" to "RESTAURER",
    "set.063" to "Rare", "set.065" to "MASQUER", "set.066" to "AFFICHER",
    "set.067" to "RECONSTRUIRE LA COUCHE DE MOTS", "set.068" to "Couche de mots reconstruite depuis le journal",
    "set.069" to "ÉCRAN TECHNIQUE", "set.070" to "RECOMMENCER", "set.071" to "Tout effacer",
    "set.072" to "Cartes, dates, statistiques, réglages et journal des réponses disparaissent. Le journal est d'abord exporté dans Documents/ikna.",
    "set.073" to "VRAIMENT TOUT EFFACER", "set.074" to "EFFACER LES DONNÉES",
    "set.075" to "Appuyez encore une fois pour confirmer. Aucun retour possible.",
    "set.076" to "le second appui efface immédiatement", "set.077" to "deux appuis nécessaires",
    "set.078" to "Recommencer ?", "set.079" to "Les dates, statistiques et la couche de mots seront remises à zéro. Le journal reste et permet de tout restaurer.",
    "set.080" to "RECOMMENCER", "set.081" to "Statistiques remises à zéro", "set.082" to "ANNULER",
    "set.083" to "FOND", "set.084" to "TEXTE", "set.085" to "ATTÉNUÉ", "set.086" to "ACCENT",
    "set.087" to "CONTRASTE · TEXTE ", "set.088" to " · ATTÉNUÉ ", "set.089" to " · ACCENT ",
    "set.090" to "un élément se lit mal sur son fond ; la couleur est tout de même appliquée",
    "set.091" to "CHARGE", "set.092" to "APPARENCE", "set.093" to "LANGUE", "set.094" to "VOIX",
    "set.095" to "POLICE", "set.096" to "RAPPEL", "set.097" to "DONNÉES", "set.098" to "RARE",
    "set.099" to "SYSTÈME", "set.100" to "РУССКИЙ", "set.101" to "SOMBRE", "set.102" to "CLAIR",
    "set.103" to "PERSONNEL", "set.104" to "POLONAIS", "set.105" to "RUSSE", "set.106" to "ANGLAIS",
    "set.107" to "ALLEMAND", "set.108" to "ESPAGNOL", "set.109" to "FRANÇAIS", "set.110" to "police",
    "set.114" to "PALETTE", "set.116" to "BRAISE", "set.117" to "BIBLIOTHÈQUE", "set.118" to "ENCRE",
    "set.119" to "PRUNE", "set.120" to "ZÉRO", "set.121" to "NEUTRE", "set.125" to "ROSE",
    "set.126" to "GIVRE", "set.127" to "PHOSPHORE", "set.141" to "ULTRAVIOLET", "set.142" to "LAGON", "set.143" to "COBALT", "set.122" to "ÉCLAIRAGE",
    "set.128" to "TOUTES LES LANGUES", "set.130" to "Voix du téléphone",
    "set.131" to "Lit les langues que vos modèles ne couvrent pas", "set.132" to "Toujours parler",
    "set.133" to "La carte se lit à chaque apparition", "set.134" to "La carte se lit uniquement au premier contact",
    "set.135" to "Cartes retirées de la rotation : ", "set.136" to "Les remettre", "set.137" to "Les cartes sont de retour",
    "set.138" to "Mises à jour", "set.139" to "L’app est installée depuis un fichier ; elle seule peut vous signaler une nouvelle version.",
    "set.140" to "MISE À JOUR", "set.123" to "BÊTA",
    "set.124" to "En bêta et désactivé par défaut : le moteur du téléphone décide du rendu, et une mauvaise voix est pire que le silence.",
    "dbg.001" to "← RETOUR", "dbg.002" to "EXPORTER LE JOURNAL DES RÉPONSES", "dbg.003" to "Fichier : Documents/ikna/",
    "dbg.004" to "Impossible d’enregistrer le fichier", "dbg.005" to "RECONSTRUIRE LA COUCHE DE MOTS",
    "dbg.006" to "Couche de mots reconstruite", "dbg.007" to "RECONSTRUIRE LE PLAN DU JOUR",
    "dbg.008" to "Plan du jour reconstruit", "dbg.009" to "Décisions du régulateur par jour",
    "dbg.010" to " nouveaux=", "dbg.011" to " dus=", "dbg.012" to " prévision3j=", "dbg.013" to " retard=",
    "dbg.014" to " précision=", "dbg.015" to " marge=",
    "deck.001" to "Aucune ligne lisible", "deck.002" to "Fragments ajoutés : ", "deck.003" to ", ignorés ",
    "deck.004" to "Paquets", "deck.005" to "Aucun paquet. Le plus en bas contient le prompt IA et l’endroit où coller le résultat.",
    "deck.006" to "lecture du fichier…", "deck.007" to "AUJOURD’HUI", "deck.008" to "rien en attente",
    "deck.009" to "aujourd’hui ", "deck.010" to "rien pour aujourd’hui", "deck.014" to "cartes", "deck.015" to "carte",
    "deck.016" to "cartes", "deck.017" to "cartes", "deck.018" to " · <1 min", "deck.019" to " min",
    "add.001" to "Nouveau paquet", "add.002" to "Un paquet est du texte brut. Une ligne par carte : expression, phrase qui la contient et traduction, séparées par |.",
    "add.003" to "Copiez le prompt et envoyez-le à n’importe quelle IA.", "add.004" to "Indiquez la langue et le thème : « polonais, cuisine, 100 cartes ».",
    "add.005" to "Copiez toute la réponse ou enregistrez-la dans un fichier.", "add.006" to "Revenez ici et collez le texte, ou choisissez le fichier.",
    "add.007" to "Copier le prompt", "add.008" to "Enregistrer le prompt", "add.009" to "Prompt copié",
    "add.010" to "Prompt enregistré", "add.011" to "Impossible d’enregistrer le prompt", "add.012" to "Collez les lignes ici",
    "add.013" to "Coller un exemple", "add.014" to "Ajouter depuis le texte", "add.015" to "Choisir un fichier",
    "add.016" to "EXPRESSION | PHRASE QUI LA CONTIENT | TRADUCTION", "add.017" to "lecture…",
    "add.018" to "Fichier trop volumineux pour un paquet", "add.019" to "Impossible de lire le fichier",
    "add.020" to "Collez d’abord le texte", "add.021" to "Cartes ajoutées : ", "add.022" to ", lignes ignorées : ",
    "add.023" to "Ligne ", "add.024" to " — ", "add.025" to "Aucune ligne utilisable", "add.026" to "Terminé",
    "add.027" to "s’habituer à|Il faut du temps pour s’habituer au bruit.|s’accoutumer\\nsurveiller|Peux-tu surveiller mon sac ?|garder à l’œil",
    "add.028" to "Exemple collé", "add.029" to "Effacer", "add.030" to "Mon paquet",
    "add.031" to "la ligne n’a pas trois parties", "add.032" to "un champ est vide", "add.033" to "l’expression n’est pas dans la phrase",
    "add.034" to "la ligne est trop longue", "add.035" to "cette expression a déjà été utilisée",
    "share.001" to "partager", "share.002" to "Envoyer le paquet", "share.003" to "partage impossible", "share.004" to "ce paquet n’a encore rien à envoyer",
    "dp.001" to "Actif", "dp.002" to "Désactivé", "dp.003" to "Langue du paquet",
    "dp.004" to "Sert à la voix. Un paquet importé prend sa langue dans ses cartes ; corrigez-la ici.",
    "dp.005" to "sans voix", "dp.006" to "Envoyer le paquet", "dp.007" to "Supprimer le paquet",
    "dp.008" to "Appuyez encore pour confirmer", "dp.009" to "Les cartes et leur planning disparaissent. Les réponses restent dans les statistiques : le journal n’est jamais réécrit.",
    "dp.010" to "Ajouter des cartes", "dp.011" to "Ajout…", "dp.013" to "Nom du paquet",
    "dp.014" to "Prononciation",
    "dp.015" to "Comment se prononce la phrase. La graphie anglaise est lisible par presque tout le monde, l’API est exacte.",
    "dp.016" to "Anglaise",
    "dp.017" to "API",
    "dp.018" to "Désactivée",
    "dp.019" to "Rien n’est affiché",
    "add.036" to "fonctionnement", "add.037" to "masquer", "add.038" to "Langue des cartes",
    "add.039" to "Utilisée uniquement pour la voix. Modifiable plus tard dans le paquet.", "add.040" to "Ce qu’il faut demander au modèle",
    "add.041" to "Nombre de cartes", "add.042" to "Langue des significations", "add.043" to "débutant",
    "add.044" to "peut tenir une conversation", "add.045" to "courant", "add.046" to "Niveau",
    "add.047" to "Thème ou situation", "add.048" to "par exemple, cafés et commande de nourriture",
    "add.049" to "Les réponses entrent dans le prompt ; il ne reste rien à saisir dans le chat.", "add.050" to "Lignes à vérifier : ",
    "add.051" to "la signification répète le terme", "add.052" to "une formulation hésitante",
    "add.053" to "cette signification apparaît déjà", "add.054" to "contient des nombres ; vérifiez-les avec la source",
    "add.055" to "Ce qui est appris", "add.056" to "une langue", "add.057" to "une matière",
    "add.058" to "Un paquet de matière n’est ni lu à voix haute ni parlé : seulement reconnu et rappelé.",
    "add.059" to "quelques bases", "add.060" to "Matière et section", "add.061" to "par exemple, neurosciences, plasticité synaptique",
    "add.062" to "Langue des cartes", "add.063" to "Coller depuis le presse-papiers", "add.064" to "Le presse-papiers ne contient aucun texte",
    "add.065" to "lignes", "add.066" to "caractères", "add.067" to "AFFICHER LE TEXTE", "add.068" to "MASQUER LE TEXTE",
    "add.069" to "et autres lignes : ", "add.070" to "les sauts de ligne ont disparu et cette ligne n’a pas pu être reconstruite. Utilisez « Coller depuis le presse-papiers » : le clavier tronque les gros collages",
    "add.071" to "Le texte dépassait la limite et a été tronqué. Divisez le paquet en deux.", "add.072" to "S’il n’existe aucun paquet prêt",
    "add.073" to "La voie facultative : demander un paquet à un modèle. Ce qui revient doit être relu.",
    "add.074" to "MÉTHODE AVEC MODÈLE", "card.002" to "touchez n’importe où", "card.003" to "← JE NE SAIS PAS", "card.004" to "JE SAIS →",
    "sess.001" to "un instant…", "sess.003" to "MINIMUM ATTEINT", "sess.004" to "Paquet terminé", "sess.005" to "C’est tout pour aujourd’hui",
    "sess.006" to "Aucune carte aujourd’hui", "sess.007" to "Plus rien à réviser ; le reste n’est pas encore dû", "sess.008" to "REVÉRIFIER",
    "sess.009" to "UN PEU PLUS +5", "sess.010" to "révisions seulement, aucun nouveau fragment", "sess.011" to "cette réponse ne peut plus être annulée",
    "sess.012" to "réponse enregistrée", "sess.013" to "ANNULER", "sess.014" to "OK", "sess.015" to "reconnaître",
    "sess.016" to "compléter", "sess.017" to "le dire à voix haute", "sess.018" to "Le plan du jour est fermé. De nouveaux fragments arriveront demain.",
    "sess.019" to "Premier jour : très peu de contenu.", "sess.020" to "Tout est révisé ; les suivantes ne sont pas encore dues.",
    "sess.021" to "Beaucoup de révisions arrivent déjà ; les nouveaux mots attendront.", "sess.022" to "Aujourd’hui, seulement les révisions les plus utiles ; le nouveau reviendra quand il y aura de la place.",
    "sess.023" to "Bon retour. Commençons par une étape courte et familière.", "sess.024" to "Une semaine calme : le nouveau peut attendre, les dates se sont déjà adaptées.",
    "sess.025" to "Trop tard pour de nouveaux fragments ; nous les verrons demain matin. Les révisions restent.", "sess.026" to "Rien de nouveau avant que l’ancien se stabilise.",
    "sess.027" to "Bon retour. Le plan s’est déjà adapté à votre rythme. Aujourd’hui, une étape courte et finie. Reprenez là où vous êtes.", "sess.028" to "J’ajoute au moins un fragment pour continuer d’avancer.",
    "sess.029" to "Plus aucun fragment nouveau ici : tous sont connus. Les révisions continueront ; pour du contenu neuf, ajoutez un paquet.",
    "sess.030" to "prochaine : aujourd’hui à ", "sess.031" to "prochaine : demain à ", "sess.032" to "prochaine : dans ",
    "sess.033" to "jours", "sess.034" to "jour", "sess.035" to "jours", "sess.036" to "jours", "sess.037" to " · <1 MIN", "sess.038" to " MIN",
    "sess.039" to "cartes", "sess.040" to "carte", "sess.041" to "cartes", "sess.042" to "cartes",
    "sess.043" to "Hier a été long : aujourd’hui sera plus léger, sans nouveauté.", "sess.044" to "MARQUER COMME FAUSSE",
    "sess.045" to "Retirée de la rotation. L’erreur n’a pas été ajoutée aux statistiques.", "sess.046" to "le terme", "sess.047" to "de mémoire",
    "onb.001" to "Des phrases, pas des mots", "onb.002" to "Des fragments prêts à l’emploi sont inclus. Les nouveaux s’ajoutent seuls ; rien à saisir à la main.",
    "onb.003" to "Sauter n’est pas échouer", "onb.004" to "Une semaine manquée ne laisse pas de tas : l'ancien revient peu à peu.",
    "onb.005" to "Le minimum est une carte", "onb.006" to "Une carte clôt la journée. « Un peu plus » n’alourdit pas demain.",
    "onb.007" to "PRÉPARATION DES CARTES…", "onb.008" to "SUIVANT", "onb.009" to "COMMENCER", "onb.010" to "PASSER",
    "onb.011" to "Gauche et droite", "onb.012" to "À gauche si vous ne savez pas, à droite si vous savez. Une réponse s'annule juste après.",
    "speaker.001" to "EXCELLENT", "speaker.002" to "BIEN", "speaker.003" to "ORDINAIRE", "speaker.004" to "FAIBLE",
    "remind.001" to "Une carte", "remind.002" to "Une seule suffit pour clôturer la journée",
    "a11y.001" to "Retour", "a11y.002" to "Réglages", "a11y.003" to "Statistiques", "a11y.004" to "Ajouter un paquet",
    "a11y.005" to "Lire à voix haute", "a11y.006" to "Paquet actif", "a11y.007" to "Expliquer ce nombre", "a11y.008" to "Je ne sais pas",
    "a11y.009" to "Je sais", "a11y.010" to "Réglages du paquet",
    "voice.001" to "Voix", "voice.002" to "Lecture actuelle", "voice.003" to "Voix du téléphone",
    "voice.004" to "Cette version n’a pas de moteur de modèle ; seule la voix du téléphone lit",
    "voice.005" to "Un modèle est installé mais ne s’est pas chargé. La voix du téléphone lit", "voice.006" to "Aucun modèle. La voix du téléphone lit",
    "voice.007" to "Vérification du modèle…", "voice.008" to "Modèle chargé et prêt", "voice.010" to "Tester la voix",
    "voice.011" to "Vos modèles", "voice.012" to "Vous fournissez le modèle : dossier Kokoro ou Piper du téléphone. Rien n’est téléchargé.",
    "voice.013" to "Supprimer le modèle", "voice.014" to "Langue du modèle", "voice.015" to "Toutes",
    "voice.016" to "Cette version n’a pas de moteur. Votre modèle ne fonctionnera pas ici ; prenez la version marquée voice.",
    "voice.017" to "Ajouter un autre modèle", "voice.018" to "Fichiers copiés : ", "voice.019" to "Ce dossier ne ressemble pas à un modèle : aucun fichier .onnx",
    "voice.020" to "Le dossier choisi est un niveau trop haut. Ouvrez-le et choisissez celui du modèle", "voice.021" to "Plusieurs modèles dans un dossier. N’en gardez qu’un",
    "voice.022" to "Aucun tokens.txt. Prenez la version sherpa-onnx, pas les fichiers Piper bruts", "voice.023" to "Copie impossible : ",
    "voice.024" to "Modèle ajouté", "voice.025" to "La lecture est désactivée ; l’interrupteur ci-dessus l’active",
    "voice.026" to "Les modèles se trouvent dans les versions sherpa-onnx, sous tts-models. Kokoro parle anglais ; Piper couvre presque toutes les langues.",
    "voice.027" to "Aucun voices.bin. Le téléchargement de Kokoro s’est arrêté trop tôt", "voice.028" to "Rien pour prononcer : ni espeak-ng-data ni lexique",
    "voice.029" to "Ajouter un modèle", "voice.030" to "Lire les cartes à voix haute", "voice.031" to "Désactivé, les cartes restent silencieuses, avec ou sans modèle",
    "voice.032" to "Qui lit quel paquet", "voice.033" to "le modèle le lit", "voice.034" to "la voix du téléphone le lit",
    "voice.035" to "personne : le modèle ignore cette langue et le téléphone n’a aucune voix", "voice.036" to "Un modèle parle une seule langue. La langue d'un paquet vient de ses cartes et se change sur sa page.",
    "voice.037" to "AUCUNE LANGUE", "voice.038" to "désactivé", "voice.039" to "Numéro de voix", "voice.040" to "Un modèle par langue",
    "voice.041" to "Ajouter une archive .tar.bz2", "voice.042" to "Ce n’est pas une archive de modèle", "voice.043" to "Espace insuffisant : décompressé, le modèle fait environ trois fois l’archive",
    "voice.044" to "L’app décompresse elle-même l’archive", "voice.045" to "Langue lue dans le nom du modèle :", "voice.046" to "AUTRE LANGUE",
    "voice.047" to "Seul le modèle connaît son nombre de voix : testez-le et le nombre apparaîtra ici.", "voice.048" to "Vitesse", "voice.049" to "Décompression :",
    "voice.050" to "Un grand modèle met plusieurs minutes à se décompresser sur le processeur du téléphone.", "voice.051" to "Vous pouvez quitter cet écran ; l’installation continue. Ne laissez pas l’app longtemps en arrière-plan.",
    "look.001" to "Apparence", "look.002" to "Lettres et couleur du carré dans la liste. Elles restent sur votre téléphone ; le destinataire ne reçoit que les cartes.",
    "look.003" to "Couleur du carré", "look.004" to "Un ou deux caractères. Vide, le carré choisit seul.", "bar.001" to "La marque ikna", "bar.003" to "Pour la main gauche",
    "upd.001" to "MISE À JOUR DISPONIBLE", "upd.002" to "Taille : ", "upd.003" to "Mo", "upd.004" to "Nouveautés :", "upd.005" to "METTRE À JOUR", "upd.006" to "PASSER",
    "upd.007" to "L’app télécharge le fichier ; la barre et le pourcentage sont ici. Android installe la nouvelle version par-dessus l’ancienne sans perdre les cartes.",
    "upd.008" to "Rechercher les mises à jour", "upd.009" to "Une requête vers la page des versions, au plus une fois par jour. Rien n’est envoyé. Désactivé, aucune connexion n’est ouverte.",
    "upd.010" to "VÉRIFIER", "upd.011" to "Installée : ", "upd.012" to "Rien de plus récent. Sans réseau, la vérification a simplement échoué ; l’app ne peut pas distinguer les deux cas.",
    "upd.013" to "PAGE DES VERSIONS", "upd.014" to "VÉRIFICATION…", "upd.015" to "Ignorée : ", "upd.016" to "Mettre à jour vers ", "upd.017" to "TÉLÉCHARGEMENT",
    "upd.018" to "Le fichier est prêt. Android installe la nouvelle version par-dessus l’ancienne ; cartes, progression et réglages restent.",
    "upd.019" to "ANNULER", "upd.020" to "INSTALLER", "upd.021" to "Android demande l’autorisation d’installer depuis cette source. Le fichier est déjà téléchargé et reste disponible.",
    "upd.022" to "AUTORISER", "upd.023" to "Échec du téléchargement : connexion coupée ou fichier incomplet. Réessayez ou utilisez le navigateur.",
    "upd.024" to "RÉESSAYER", "upd.025" to "DANS LE NAVIGATEUR",
    "cat.001" to "Catalogue de paquets", "cat.002" to "Les phrases viennent de Tatoeba, les formes des mots de Wiktionnaire. La licence et le crédit sont affichés avant le téléchargement.",
    "cat.003" to "CHARGEMENT DE LA LISTE…", "cat.004" to "La liste n’est pas arrivée : pas de réseau ou catalogue inaccessible. Rien n’est cassé ; le paquet intégré et la création par modèle restent disponibles.",
    "cat.005" to "PAGE DU CATALOGUE", "cat.006" to "RÉESSAYER", "cat.007" to "À apprendre", "cat.008" to "Significations en", "cat.009" to "Thème", "cat.010" to "Niveau", "cat.011" to "TOUS",
    "cat.012" to "Cette paire est bien couverte : beaucoup de phrases et de grands paquets.", "cat.013" to "Cette paire est peu fournie : le corpus contient peu de phrases. C’est une limite de la source, pas de l’app.",
    "cat.014" to "Rien pour cette paire pour l’instant. Le README indique la couverture de chaque paire.", "cat.015" to "cartes", "cat.016" to "Licence : ", "cat.017" to "Source : ",
    "cat.018" to "TÉLÉCHARGER", "cat.019" to "TÉLÉCHARGEMENT", "cat.020" to "Échec du téléchargement : connexion coupée ou fichier incomplet. Rien n’a été installé.",
    "cat.021" to "Le fichier est arrivé, mais aucune carte n’a pu être créée. Aucun paquet ajouté.", "cat.022" to "Terminé. Cartes dans le paquet : ", "cat.023" to "CONSTRUCTION DU PAQUET…",
    "cat.024" to "Mo", "cat.025" to "CC BY-SA : un paquet dérivé et partagé conserve la même licence. L’étudier ne vous impose rien.", "cat.026" to "Liste créée : ",
    "cat.027" to "débutant", "cat.028" to "intermédiaire", "cat.029" to "avancé", "cat.030" to "Aucun résultat pour ces filtres.",
    "cat.031" to "Un paquet prêt", "cat.032" to "Si parler à un modèle ne vaut pas l’effort : paquet du catalogue, phrases humaines, licence ouverte et auteur indiqué.",
    "cat.033" to "OUVRIR LE CATALOGUE", "cat.034" to "DÉJÀ TÉLÉCHARGÉ", "cat.035" to "télécharger à nouveau",
    "cat.036" to "AFFICHER DES EXEMPLES", "cat.037" to "CHARGEMENT DES EXEMPLES…", "cat.038" to "RÉESSAYER LES EXEMPLES",
    "cat.039" to "EXEMPLES DU PAQUET", "cat.040" to "CARTE ", "cat.041" to "Avec prononciation", "a11y.011" to "Rechercher des paquets",
    "src.001" to "Source · ", "src.002" to "Cette carte est incorrecte ?", "src.003" to "La carte sera masquée et un rapport prêt à coller avec son texte et sa source sera copié pour GitHub Issues.",
    "src.004" to "MASQUER ET COPIER", "src.005" to "ANNULER", "src.006" to "Carte masquée · rapport copié", "src.007" to "SOURCE",
    "search.001" to "Rechercher des paquets", "search.002" to "Recherche uniquement dans les paquets installés sur ce téléphone. Aucun réseau.",
    "search.003" to "Expression, phrase ou traduction", "search.004" to "RECHERCHER", "search.005" to "RECHERCHE…", "search.006" to "Saisissez au moins deux caractères.",
    "search.007" to "Aucun résultat dans les paquets installés.", "search.008" to "Les 80 premiers résultats sont affichés ; précisez la recherche pour réduire la liste.",
    "search.009" to "La recherche a échoué. Aucune donnée n’a changé ; vous pouvez réessayer.", "search.010" to "PAQUET · ",
    "mig.001" to "Mise à jour du planning", "mig.002" to "Paquets et historique restent en place. Les réponses sont rejouées une fois avec FSRS-6.",
    "mig.003" to "Le planning n’a pas été mis à jour", "mig.004" to "Rien n’a été supprimé. Vous pouvez relancer le calcul sans risque.", "mig.005" to "RÉESSAYER",
    "diag.001" to "Diagnostic", "diag.002" to "Un résumé technique seulement : sans noms de paquets, texte des cartes ni historique. Rien n'est envoyé.",
    "diag.003" to "AFFICHER LE DIAGNOSTIC", "diag.004" to "MASQUER LE DIAGNOSTIC", "diag.005" to "COLLECTE…",
    "diag.006" to "COPIER LE RÉSUMÉ", "diag.007" to "Diagnostic copié", "diag.008" to "Impossible de collecter le diagnostic",

    "anki.001" to "Depuis Anki",
    "anki.002" to "Choisissez un fichier .apkg. Tout reste sur ce téléphone.",
    "anki.003" to "N'importe quel .apkg d'Anki convient, ancien ou récent.",
    "anki.005" to "CHOISIR .APKG",
    "anki.006" to "LECTURE DU FICHIER…",
    "anki.007" to "Vous pouvez quitter cet écran ; l’import continue.",
    "anki.008" to "Paquets : ",
    "anki.009" to "Cartes : ",
    "anki.010" to "Événements ajoutés : ",
    "anki.011" to "Entrées d’historique ignorées : ",
    "anki.012" to "Suspendues ou enfouies dans Anki, non ajoutées : ",
    "anki.013" to "Cartes ignorées : ",
    "anki.014" to "Avec images ou son : ",
    "anki.015" to "L’historique est très grand : les 100 000 dernières notes ont été utilisées.",
    "anki.016" to "TERMINÉ",
    "anki.017" to "IMPORTER UN AUTRE",
    "anki.018" to "Impossible de lire ce .apkg.",
    "anki.019" to "Le paquet ne contient aucune collection Anki.",
    "anki.020" to "Cette collection n'a pas pu être lue. Rien n'a changé.",
    "anki.021" to "Le fichier est endommagé, ou son format n’est pas encore lisible.",
    "anki.022" to "Le paquet dépasse la limite sûre de 300 Mo. Aucune donnée n’a changé.",
    "anki.023" to "Le paquet ne contient aucune carte texte lisible. Aucune donnée n’a changé.",
    "anki.024" to "Rien n’a changé : corrigez l’export et réessayez.",
    "anki.025" to "Ce qui est arrivé",
    "anki.026" to "Importez un .apkg sur le téléphone : paquets et historique sans reconstruction manuelle.",
    "anki.027" to "IMPORTER DEPUIS ANKI",
    "anki.028" to "Le calendrier est reconstruit ici ; les intervalles d’Anki ne sont pas repris.",
    "anki.029" to "Le fichier Anki d’origine n’est pas modifié.",
    "anki.030" to "Récupérées des champs : ",
    "anki.031" to "Le fichier ne contient que la carte d'avertissement d'Anki. Exportez-le à nouveau.",
    "anki.032" to "Langues : ",
    "anki.033" to "matière",
    "anki.034" to "indéterminée",
    "pc.001" to "Pas encore disponible sur ordinateur",
    "pc.002" to "Espace révèle, 1–4 note, Z annule",
    "pc.003" to "Séance",
    "pc.004" to "Choisissez un paquet à gauche",
    "pc.005" to "Fichier",
    "pc.006" to "Affichage",
    "pc.007" to "Aide",
    "pc.008" to "Quitter",
    "pc.009" to "Plein écran",
    "pc.010" to "Raccourcis clavier",
    "pc.011" to "Dossier de données",
    "pc.012" to "Ikna est déjà lancée",
    "pc.013" to "Ikna a rencontré une erreur. Les détails sont dans le fichier journal :",
    "pc.014" to "Faites glisser la carte : à gauche je ne sais pas, à droite je sais",
    "pc.015" to "Paquets",
    "pc.016" to "Aujourd'hui",
)
