package dev.ikna.ui.text

/** Complete Brazilian Portuguese interface catalogue. */
val STRINGS_PT: Map<String, String> = linkedMapOf(
    "app.001" to "Lembrete",
    "app.002" to "Um lembrete por dia, somente se a meta mínima ainda não tiver sido concluída",
    "font.001" to "Não foi possível ler o arquivo",
    "font.002" to "Esse arquivo é grande demais para ser uma fonte",
    "font.003" to "Não foi possível salvar a fonte",
    "font.004" to "Não foi possível salvar a fonte",
    "font.005" to "Esse não é um arquivo de fonte",
    "font.006" to "Essa é uma coleção de fontes .ttc — é necessário um único arquivo .ttf ou .otf",
    "font.007" to "Essa é uma fonte da Web .woff — o Android não consegue lê-la; use .ttf ou .otf",
    "font.008" to "Esse não é um arquivo de fonte",
    "font.009" to "O arquivo da fonte está corrompido",
    "font.010" to "O arquivo da fonte está incompleto",
    "font.011" to "O arquivo da fonte está incompleto",
    "font.012" to "A fonte não tem tabela de caracteres",
    "font.013" to "A fonte não contém letras",
    "deckrepo.001" to "Seu próprio baralho",
    "stats.001" to "Estatísticas",
    "stats.002" to "ÚLTIMOS 30 DIAS",
    "stats.003" to "Cada marca é um dia com uma sessão; hoje fica à direita. Pular não zera nem interrompe nada: não há sequência aqui, portanto não há nada para quebrar.",
    "stats.004" to "META DIÁRIA",
    "stats.005" to "Cartões por dia. Calculada com base nos seus dias recentes e recalculada automaticamente.",
    "stats.006" to "É uma estimativa inicial, não uma medição. Vou calcular o seu próprio número quando houver pelo menos três dias com sessões — antes disso, seria apenas um palpite.",
    "stats.007" to "PALAVRAS NA MEMÓRIA",
    "stats.008" to "RESPONDIDOS HOJE",
    "stats.009" to "As palavras são contadas separadamente dos blocos: uma palavra aparece em frases diferentes e permanece na memória melhor do que qualquer uma delas.",
    "stats.010" to "PREVISTOS PARA OS PRÓXIMOS 14 DIAS",
    "stats.011" to "Quantos cartões vencerão. Se surgir uma montanha em algum ponto, novos blocos não serão adicionados nesses dias.",
    "stats.012" to "RETENÇÃO",
    "stats.013" to "São necessárias pelo menos 20 revisões para que isto seja um dado, e não um palpite. Até agora há ",
    "stats.014" to "De ",
    "stats.015" to " revisões neste mês, você se lembrou de ",
    "stats.016" to "%. Só as revisões contam — um primeiro contato não pode ser esquecido.",
    "stats.017" to "O cronograma busca cerca de 90%. Abaixo de 80%, os intervalos estão longos demais para você. A carga se ajusta sozinha, mas, se continuar assim por semanas, escolha uma meta menor.",
    "stats.018" to "O cronograma busca cerca de 90%. Acima de 95%, há mais revisões do que o necessário: a memória aguentaria passagens menos frequentes, e isso representa minutos que poderiam ser poupados.",
    "stats.019" to "O cronograma busca cerca de 90% e, neste momento, tudo está dentro dessa faixa. Não é preciso mexer em nada.",
    "stats.020" to "MINUTOS HOJE",
    "stats.021" to "ESTA SEMANA",
    "stats.022" to "Só conta o tempo em que um cartão está na tela: pausas com o telefone de lado não entram aqui. Cada cartão leva cerca de ",
    "stats.023" to " s.",
    "stats.024" to "Só conta o tempo em que um cartão está na tela: pausas com o telefone de lado não entram aqui.",
    "stats.025" to "QUANDO FUNCIONA MELHOR",
    "stats.026" to "A recordação funciona melhor por volta das ",
    "stats.027" to ". Isso não é uma ordem para estudar exatamente nesse horário — significa apenas que, para você, custa menos nessa hora, e faz sentido definir um lembrete uma hora antes.",
    "stats.028" to "Ainda é cedo para apontar um horário: são necessárias pelo menos 12 revisões dentro de uma mesma hora. As barras claras são horários com poucos dados.",
    "stats.029" to "NÃO VAI FIXAR",
    "stats.030" to "Nenhum até agora: nada foi esquecido quatro vezes ou mais.",
    "stats.031" to "À direita: quantas vezes a frase foi esquecida. Isso diz respeito à frase, não a você.",
    "stats.032" to "HOJE",
    "set.001" to "Não foi possível abrir o arquivo",
    "set.002" to "Não foi possível abrir o arquivo",
    "set.003" to "Fonte aplicada: ",
    "set.004" to "Sem permissão para notificações, o lembrete não chegará",
    "set.005" to "O arquivo de configurações está corrompido",
    "set.006" to "Configurações restauradas",
    "set.007" to "Configurações restauradas. A fonte «",
    "set.008" to "» precisa ser escolhida novamente — o arquivo da fonte é seu e não é incluído no backup.",
    "set.009" to "Respostas adicionadas: ",
    "set.010" to " · recalculadas ",
    "set.011" to " · ignoradas ",
    "set.012" to "Configurações",
    "set.013" to "Carga",
    "set.015" to "AUTOMÁTICA",
    "set.016" to "MANUAL",
    "set.017" to "AGORA · ",
    "set.018" to "CARTÕES POR DIA",
    "set.019" to "Aparência",
    "set.020" to "Animações",
    "set.022" to "Vibração",
    "set.024" to "Idioma",
    "set.026" to "Leitura em voz alta",
    "set.027" to "O mecanismo que já está no telefone faz a leitura. Nada é baixado e nada vai para a rede.",
    "set.028" to "Ler em voz alta",
    "set.029" to "O símbolo de som só aparece quando não entrega a resposta",
    "set.030" to "verificando o que há no telefone…",
    "set.031" to "Não há mecanismo de voz no telefone. Qualquer opção offline serve — RHVoice ou SherpaTTS do F-Droid, por exemplo. Volte aqui depois de instalar.",
    "set.032" to "CONFIGURAÇÕES DO MECANISMO DE VOZ",
    "set.033" to "Não foi possível encontrar essa seção nas configurações do telefone",
    "set.034" to "Há um mecanismo, mas ele não tem vozes offline para estes idiomas. Elas precisam ser baixadas uma vez; depois disso, funcionam sem rede.",
    "set.035" to "INSTALAR VOZES",
    "set.036" to "O mecanismo não consegue baixar vozes sozinho — procure nas configurações dele",
    "set.037" to "sem vozes offline para este idioma",
    "set.038" to "PADRÃO",
    "set.039" to "O primeiro som após iniciar pode levar um segundo — o mecanismo está despertando.",
    "set.040" to "Fonte",
    "set.041" to "Sua própria fonte .ttf ou .otf para o texto dos cartões. O arquivo é verificado antes de ser aplicado.",
    "set.042" to "AGORA · SISTEMA",
    "set.043" to "AGORA · ",
    "set.044" to "ESCOLHER ARQUIVO",
    "set.045" to "REDEFINIR",
    "set.046" to "A fonte do sistema foi restaurada",
    "set.047" to "Lembrete",
    "set.049" to "Lembrar",
    "set.050" to "às ",
    "set.051" to "desativado",
    "set.052" to "Dados",
    "set.053" to "O registro de respostas é a única coisa que não pode ser recuperada. Todo o resto é recalculado a partir dele.",
    "set.054" to "Exportar automaticamente uma vez por semana",
    "set.055" to "Para a pasta Documents/ikna",
    "set.056" to "EXPORTAR",
    "set.057" to "Não foi possível salvar o arquivo",
    "set.058" to "Configurações salvas. O registro ainda está vazio — não há nada para exportar.",
    "set.059" to "Registro e configurações salvos em Documents/ikna",
    "set.060" to "RESTAURAR",
    "set.063" to "Raro",
    "set.065" to "OCULTAR",
    "set.066" to "MOSTRAR",
    "set.067" to "RECONSTRUIR A CAMADA DE PALAVRAS",
    "set.068" to "Camada de palavras reconstruída a partir do registro",
    "set.069" to "TELA TÉCNICA",
    "set.070" to "RECOMEÇAR",
    "set.071" to "Apagar tudo",
    "set.072" to "Cartões, datas, estatísticas, configurações e o registro de respostas serão apagados. Antes disso, o registro será exportado para Documents/ikna.",
    "set.073" to "REALMENTE APAGAR TUDO",
    "set.074" to "APAGAR OS DADOS",
    "set.075" to "Pressione de novo se realmente quiser fazer isso. Não será possível desfazer.",
    "set.076" to "o segundo toque apaga imediatamente",
    "set.077" to "são necessários dois toques",
    "set.078" to "Recomeçar?",
    "set.079" to "As datas dos cartões, as estatísticas e a camada de palavras serão zeradas. O registro de respostas permanece — tudo pode ser recuperado por ele com o botão «Restaurar».",
    "set.080" to "RECOMEÇAR",
    "set.081" to "Estatísticas zeradas",
    "set.082" to "CANCELAR",
    "set.083" to "FUNDO",
    "set.084" to "TEXTO",
    "set.085" to "SUAVE",
    "set.086" to "DESTAQUE",
    "set.087" to "CONTRASTE · TEXTO ",
    "set.088" to "  ·  SUAVE ",
    "set.089" to "  ·  DESTAQUE ",
    "set.090" to "alguma coisa aqui fica difícil de ler sobre o próprio fundo — a cor ainda será aplicada",
    "set.091" to "CARGA",
    "set.092" to "APARÊNCIA",
    "set.093" to "IDIOMA",
    "set.094" to "VOZ",
    "set.095" to "FONTE",
    "set.096" to "LEMBRETE",
    "set.097" to "DADOS",
    "set.098" to "RARO",
    "set.099" to "SISTEMA",
    "set.100" to "РУССКИЙ",
    "set.101" to "ESCURO",
    "set.102" to "CLARO",
    "set.103" to "PRÓPRIO",
    "set.104" to "POLONÊS",
    "set.105" to "RUSSO",
    "set.106" to "INGLÊS",
    "set.107" to "ALEMÃO",
    "set.108" to "ESPANHOL",
    "set.109" to "FRANCÊS",
    "set.110" to "fonte",
    "set.114" to "PALETA",
    "set.116" to "BRASA",
    "set.117" to "BIBLIOTECA",
    "set.118" to "TINTA",
    "set.119" to "AMEIXA",
    "set.120" to "ZERO",
    "set.121" to "NEUTRA",
    "set.125" to "ROSA",
    "set.126" to "GELO",
    "set.127" to "FÓSFORO",
    "set.141" to "ULTRAVIOLETA",
    "set.142" to "LAGOA",
    "set.143" to "COBALTO",
    "set.122" to "ILUMINAÇÃO",
    "set.128" to "TODOS OS IDIOMAS",
    "set.130" to "Voz do telefone",
    "set.131" to "Lê os idiomas que nenhum dos seus modelos lê",
    "set.132" to "Falar sempre",
    "set.133" to "O cartão é lido toda vez que aparece",
    "set.134" to "O cartão é lido somente no primeiro contato",
    "set.135" to "Cartões retirados da rotação: ",
    "set.136" to "Colocar de volta",
    "set.137" to "Os cartões voltaram",
    "set.138" to "Atualizações",
    "set.139" to "O aplicativo é instalado por um arquivo, então somente o próprio aplicativo pode avisar que existe uma versão mais recente.",
    "set.140" to "ATUALIZAR",
    "set.123" to "BETA",
    "set.124" to "Em beta e desativado por padrão: o som da voz é definido pelo mecanismo do telefone, e uma voz ruim é pior do que o silêncio.",
    "dbg.001" to "← VOLTAR",
    "dbg.002" to "EXPORTAR O REGISTRO DE RESPOSTAS",
    "dbg.003" to "Arquivo: Documents/ikna/",
    "dbg.004" to "Não foi possível salvar o arquivo",
    "dbg.005" to "RECONSTRUIR A CAMADA DE PALAVRAS",
    "dbg.006" to "Camada de palavras reconstruída",
    "dbg.007" to "RECONSTRUIR O PLANO DE HOJE",
    "dbg.008" to "Plano de hoje reconstruído",
    "dbg.009" to "Decisões do regulador por dia",
    "dbg.010" to "  novas=",
    "dbg.011" to "  devidas=",
    "dbg.012" to "  previsão3d=",
    "dbg.013" to "  pendentes=",
    "dbg.014" to "  precisão=",
    "dbg.015" to "  folga=",
    "deck.001" to "Não foi possível ler nenhuma linha",
    "deck.002" to "Blocos adicionados: ",
    "deck.003" to ", ignorados ",
    "deck.004" to "Baralhos",
    "deck.005" to "Ainda não há baralhos. O botão de mais na parte inferior contém o prompt para IA e um espaço para colar.",
    "deck.006" to "lendo o arquivo…",
    "deck.007" to "HOJE",
    "deck.008" to "nada esperando",
    "deck.009" to "hoje ",
    "deck.010" to "nada para hoje",
    "deck.014" to "cartões",
    "deck.015" to "cartão",
    "deck.016" to "cartões",
    "deck.017" to "cartões",
    "deck.018" to " · <1 min",
    "deck.019" to " min",
    "add.001" to "Novo baralho",
    "add.002" to "Um baralho é texto simples. Cada linha é um cartão: uma expressão, uma frase que a contenha e a tradução, separadas por |.",
    "add.003" to "Copie o prompt e envie para qualquer IA.",
    "add.004" to "Informe o idioma e o tema: “Polonês, culinária, 100 cartões”.",
    "add.005" to "Copie a resposta inteira ou salve-a como arquivo.",
    "add.006" to "Volte aqui e cole o texto ou escolha o arquivo.",
    "add.007" to "Copiar o prompt",
    "add.008" to "Salvar o prompt como arquivo",
    "add.009" to "Prompt copiado",
    "add.010" to "Prompt salvo",
    "add.011" to "Não foi possível salvar o prompt",
    "add.012" to "Cole aqui as linhas do baralho",
    "add.013" to "Colar um exemplo",
    "add.014" to "Adicionar do texto",
    "add.015" to "Escolher arquivo",
    "add.016" to "EXPRESSÃO | FRASE QUE A CONTÉM | TRADUÇÃO",
    "add.017" to "lendo…",
    "add.018" to "Esse arquivo é grande demais para ser um baralho",
    "add.019" to "Não foi possível ler o arquivo",
    "add.020" to "Cole o texto primeiro",
    "add.021" to "Cartões adicionados: ",
    "add.022" to ", linhas ignoradas: ",
    "add.023" to "Linha ",
    "add.024" to " — ",
    "add.025" to "Nenhuma linha pôde ser usada",
    "add.026" to "Concluído",
    "add.027" to "get used to|It takes a while to get used to the noise.|acostumar-se\nkeep an eye on|Can you keep an eye on my bag?|ficar de olho",
    "add.028" to "Exemplo colado",
    "add.029" to "Limpar",
    "add.030" to "Meu baralho",
    "add.031" to "a linha não tem três partes",
    "add.032" to "um campo vazio",
    "add.033" to "a expressão não aparece na frase",
    "add.034" to "a linha é longa demais",
    "add.035" to "essa expressão já foi usada",
    "share.001" to "compartilhar",
    "share.002" to "Enviar baralho",
    "share.003" to "não foi possível compartilhar",
    "share.004" to "este baralho ainda não tem nada para enviar",
    "dp.001" to "Em uso",
    "dp.002" to "Desativado",
    "dp.003" to "Idioma do baralho",
    "dp.004" to "Usado para a voz. Um baralho importado herda o idioma dos cartões — altere aqui se estiver incorreto.",
    "dp.005" to "sem voz",
    "dp.006" to "Enviar baralho",
    "dp.007" to "Excluir baralho",
    "dp.008" to "Toque novamente se realmente quiser fazer isso",
    "dp.009" to "Os cartões deste baralho e seus agendamentos serão removidos. As respostas permanecem nas estatísticas — esse registro nunca é reescrito.",
    "dp.010" to "Adicionar cartões",
    "dp.011" to "Adicionando…",
    "dp.013" to "Nome do baralho",
    "dp.014" to "Pronúncia",
    "dp.015" to "Como a expressão soa. A grafia inglesa é legível para quase todos; o AFI é exato.",
    "dp.016" to "Inglês",
    "dp.017" to "AFI",
    "dp.018" to "Desativada",
    "dp.019" to "Nenhuma linha é exibida",
    "add.036" to "como funciona",
    "add.037" to "ocultar",
    "add.038" to "Em qual idioma estão os cartões",
    "add.039" to "Usado somente para a voz. Pode ser alterado depois na página do próprio baralho.",
    "add.040" to "O que pedir ao modelo",
    "add.041" to "Quantos cartões",
    "add.042" to "Idioma dos significados",
    "add.043" to "iniciante",
    "add.044" to "consegue manter uma conversa",
    "add.045" to "fluente",
    "add.046" to "Nível",
    "add.047" to "Tema ou situação",
    "add.048" to "por exemplo, cafés e pedir comida",
    "add.049" to "As respostas entram no próprio prompt, então não resta nada para digitar no chat.",
    "add.050" to "Vale a pena verificar, linhas: ",
    "add.051" to "o significado repete o próprio termo",
    "add.052" to "uma formulação imprecisa",
    "add.053" to "este significado já apareceu acima",
    "add.054" to "contém números — confira com a fonte",
    "add.055" to "O que será aprendido",
    "add.056" to "um idioma",
    "add.057" to "um assunto",
    "add.058" to "Um baralho de assunto não é lido em voz alta e nunca pede que você fale — apenas que reconheça e recorde.",
    "add.059" to "algum conhecimento prévio",
    "add.060" to "Assunto e seção",
    "add.061" to "por exemplo, neurociência, plasticidade sináptica",
    "add.062" to "Idioma dos cartões",
    "add.063" to "Colar da área de transferência",
    "add.064" to "A área de transferência não contém texto",
    "add.065" to "linhas",
    "add.066" to "caracteres",
    "add.067" to "MOSTRAR O TEXTO",
    "add.068" to "OCULTAR O TEXTO",
    "add.069" to "e mais linhas: ",
    "add.070" to "as quebras de linha se perderam ao colar, e esta linha não pôde ser reconstruída. Pressione “colar da área de transferência”: o teclado corta colagens grandes",
    "add.071" to "O texto ultrapassou o limite e foi cortado. Divida o baralho em dois.",
    "add.072" to "Se não houver um baralho pronto",
    "add.073" to "O caminho opcional: pedir a um modelo que escreva um baralho. O resultado precisa ser conferido visualmente.",
    "add.074" to "O CAMINHO DO MODELO",
    "card.002" to "toque em qualquer lugar",
    "card.003" to "← NÃO SEI",
    "card.004" to "SEI →",
    "sess.001" to "um momento…",
    "sess.003" to "MÍNIMO CONCLUÍDO",
    "sess.004" to "Baralho concluído",
    "sess.005" to "Isso é tudo por hoje",
    "sess.006" to "Nenhum cartão hoje",
    "sess.007" to "Não há mais nada para revisar — o restante ainda não venceu",
    "sess.008" to "VERIFICAR NOVAMENTE",
    "sess.009" to "MAIS UM POUCO  +5",
    "sess.010" to "somente revisões; nenhum bloco novo vem daqui",
    "sess.011" to "esta resposta não pode mais ser desfeita",
    "sess.012" to "resposta registrada",
    "sess.013" to "DESFAZER",
    "sess.014" to "OK",
    "sess.015" to "reconhecer",
    "sess.016" to "completar",
    "sess.017" to "dizer em voz alta",
    "sess.018" to "O plano do dia foi encerrado. Novos blocos virão sozinhos amanhã.",
    "sess.019" to "Primeiro dia — vamos pegar bem pouco.",
    "sess.020" to "Tudo foi revisado; os próximos ainda não venceram.",
    "sess.021" to "Já há muitas revisões pela frente — as palavras novas podem esperar.",
    "sess.022" to "Hoje, somente as revisões mais úteis; o material novo volta quando houver espaço.",
    "sess.023" to "Boas-vindas de volta. Vamos começar com um passo curto e familiar.",
    "sess.024" to "Uma semana tranquila — o material novo pode esperar; as datas já se adaptaram.",
    "sess.025" to "Tarde demais para blocos novos — vamos encontrá-los pela manhã; as revisões permanecem.",
    "sess.026" to "Até o conteúdo antigo se firmar, nada de novo.",
    "sess.027" to "Boas-vindas de volta. O plano já se adaptou ao seu ritmo. Hoje é um passo curto e finito. Continue de onde você está agora.",
    "sess.028" to "Vou adicionar pelo menos um bloco novo para não ficarmos parados.",
    "sess.029" to "Não há mais blocos novos aqui — todos já são familiares. As revisões continuarão nas datas certas; para ter material novo, é preciso adicionar outro baralho.",
    "sess.030" to "próximo — hoje às ",
    "sess.031" to "próximo — amanhã às ",
    "sess.032" to "próximo — em ",
    "sess.033" to "dias",
    "sess.034" to "dia",
    "sess.035" to "dias",
    "sess.036" to "dias",
    "sess.037" to " · <1 MIN",
    "sess.038" to " MIN",
    "sess.039" to "cartões",
    "sess.040" to "cartão",
    "sess.041" to "cartões",
    "sess.042" to "cartões",
    "sess.043" to "Ontem foi mais longo — hoje será um dia mais leve, sem nada novo.",
    "sess.044" to "MARCAR COMO ERRADO",
    "sess.045" to "Retirado da rotação. O erro não foi registrado nas suas estatísticas.",
    "sess.046" to "o termo",
    "sess.047" to "de memória",
    "onb.001" to "Esta é a",
    "onb.002" to "Eu criei a ikna porque o mercado atual de aplicativos SRS é moldado principalmente por equipes de marketing que não se importam com o quanto você consegue aprender nem com a eficiência do aprendizado. Outro motivo é que hoje não existem aplicativos para estudar matérias e idiomas desenvolvidos para pessoas neurodivergentes, por exemplo, pessoas com TDAH. Quero ajudar você a evitar os problemas que podem surgir em outros aplicativos ao tentar aprender ou dominar alguma coisa.",
    "onb.003" to "Todos os dias, o aplicativo monta um plano finito.",
    "onb.004" to "Quando o plano termina, isso é tudo por hoje. A quantidade de cartões muda gradualmente e depende dos dias anteriores.",
    "onb.005" to "Primeiro, experimente o aplicativo e decida se você precisa dele.",
    "onb.006" to "Um erro aqui não pune você. Ele ajuda o aplicativo a programar corretamente a próxima revisão.",
    "onb.007" to "PREPARANDO OS CARTÕES…",
    "onb.008" to "PRÓXIMO",
    "onb.009" to "COMEÇAR",
    "onb.010" to "PULAR",
    "onb.011" to "O progresso fica armazenado no dispositivo.",
    "onb.012" to "Você pode exportá-lo, transferi-lo ou apagá-lo completamente nas configurações. Estou aberto a críticas e apoiarei suas ideias se elas forem úteis. Vamos começar com uma primeira sessão curta.",
    "speaker.001" to "EXCELENTE",
    "speaker.002" to "BOA",
    "speaker.003" to "NORMAL",
    "speaker.004" to "BAIXA",
    "remind.001" to "Um cartão",
    "remind.002" to "Um basta para encerrar o dia",
    "a11y.001" to "Voltar",
    "a11y.002" to "Configurações",
    "a11y.003" to "Estatísticas",
    "a11y.004" to "Adicionar um baralho",
    "a11y.005" to "Ler em voz alta",
    "a11y.006" to "Baralho em uso",
    "a11y.007" to "Explicar este número",
    "a11y.008" to "Não sei",
    "a11y.009" to "Sei",
    "a11y.010" to "Configurações do baralho",
    "voice.001" to "Voz",
    "voice.002" to "Lendo agora",
    "voice.003" to "A voz do próprio telefone",
    "voice.004" to "Esta versão não inclui mecanismo de modelo — somente a voz do telefone faz a leitura",
    "voice.005" to "Um modelo está instalado, mas não carregou. A voz do telefone faz a leitura",
    "voice.006" to "Sem modelo. A voz do próprio telefone faz a leitura",
    "voice.007" to "Verificando o modelo…",
    "voice.008" to "O modelo está carregado e pronto",
    "voice.010" to "Testar a voz",
    "voice.011" to "Seus modelos",
    "voice.012" to "Você fornece o modelo: uma pasta do Kokoro ou Piper no telefone. Nada é baixado — o aplicativo não tem acesso à internet.",
    "voice.013" to "Remover o modelo",
    "voice.014" to "Idioma do modelo",
    "voice.015" to "Qualquer um",
    "voice.016" to "Esta versão não tem mecanismo. Seu próprio modelo não funcionará aqui — use a versão marcada como voice.",
    "voice.017" to "Adicionar outro modelo",
    "voice.018" to "Arquivos copiados: ",
    "voice.019" to "Isto não parece um modelo: não há arquivo .onnx na pasta",
    "voice.020" to "A pasta escolhida está um nível acima. Abra-a e selecione a pasta que contém o modelo",
    "voice.021" to "Há vários modelos em uma pasta. Deixe apenas um",
    "voice.022" to "Não há tokens.txt. Use a versão sherpa-onnx do modelo, não os arquivos brutos do Piper",
    "voice.023" to "Não foi possível copiar: ",
    "voice.024" to "Modelo adicionado",
    "voice.025" to "A leitura em voz alta está desativada — o interruptor acima a ativa",
    "voice.026" to "Os modelos ficam na página de lançamentos do sherpa-onnx, em tts-models. O Kokoro fala inglês; o Piper cobre quase qualquer idioma, inclusive russo e polonês.",
    "voice.027" to "Não há voices.bin. O download do Kokoro foi interrompido antes de terminar",
    "voice.028" to "Não há como pronunciar: faltam espeak-ng-data e um léxico",
    "voice.029" to "Adicionar um modelo",
    "voice.030" to "Ler os cartões em voz alta",
    "voice.031" to "Enquanto isto estiver desativado, os cartões ficam em silêncio, com ou sem modelo",
    "voice.032" to "Quem lê cada baralho",
    "voice.033" to "o modelo faz a leitura",
    "voice.034" to "a voz do telefone faz a leitura",
    "voice.035" to "ninguém: o modelo não conhece este idioma e o telefone não tem uma voz para ele",
    "voice.036" to "Um modelo fala um idioma. O idioma de um baralho vem dos cartões e pode ser alterado no próprio baralho.",
    "voice.037" to "SEM IDIOMA",
    "voice.038" to "desativado",
    "voice.039" to "Número da voz",
    "voice.040" to "Um modelo fala cada idioma",
    "voice.041" to "Adicionar um arquivo .tar.bz2",
    "voice.042" to "Isto não é um arquivo de modelo",
    "voice.043" to "Espaço insuficiente: um modelo descompactado ocupa cerca de três vezes o tamanho do arquivo",
    "voice.044" to "O aplicativo descompacta o arquivo sozinho",
    "voice.045" to "Idioma identificado pelo nome do modelo:",
    "voice.046" to "OUTRO IDIOMA",
    "voice.047" to "Só o próprio modelo pode informar quantas vozes possui: pressione o botão de teste e o número aparecerá aqui.",
    "voice.048" to "Velocidade",
    "voice.049" to "Descompactando:",
    "voice.050" to "Um modelo grande leva alguns minutos para descompactar: o bzip2 é processado pelo próprio telefone.",
    "voice.051" to "Você pode sair desta tela — a instalação continua. Não deixe o aplicativo em segundo plano por muito tempo.",
    "look.001" to "Aparência",
    "look.002" to "As letras e a cor do quadrado na lista de baralhos. Só suas: quem receber o baralho recebe os cartões e nada mais.",
    "look.003" to "Cor do quadrado",
    "look.004" to "Um ou dois caracteres. Se ficar vazio, o quadrado escolhe sozinho.",
    "bar.001" to "A marca da Ikna",
    "bar.003" to "Para a mão esquerda",
    "upd.001" to "ATUALIZAÇÃO DISPONÍVEL",
    "upd.002" to "Tamanho: ",
    "upd.003" to "MB",
    "upd.004" to "Novidades:",
    "upd.005" to "ATUALIZAR",
    "upd.006" to "PULAR",
    "upd.007" to "O aplicativo baixa o arquivo sozinho; a barra e a porcentagem aparecem aqui. O instalador do Android coloca a nova versão sobre a antiga, e os cartões e o progresso permanecem.",
    "upd.008" to "Verificar atualizações",
    "upd.009" to "Uma solicitação à página de lançamentos, no máximo uma vez por dia. Nada é enviado. Se estiver desativado, nenhuma conexão é aberta.",
    "upd.010" to "VERIFICAR AGORA",
    "upd.011" to "Instalada: ",
    "upd.012" to "Nada mais recente. Se não houver rede, a verificação simplesmente falhou — o aplicativo não consegue distinguir as duas situações.",
    "upd.013" to "PÁGINA DE LANÇAMENTOS",
    "upd.014" to "VERIFICANDO…",
    "upd.015" to "Ignorada: ",
    "upd.016" to "Atualizar para ",
    "upd.017" to "BAIXANDO",
    "upd.018" to "O arquivo está aqui. O instalador do Android coloca a nova versão sobre a antiga — cartões, progresso e configurações permanecem.",
    "upd.019" to "CANCELAR",
    "upd.020" to "INSTALAR",
    "upd.021" to "O Android pede permissão para instalar aplicativos desta fonte; sem ela, o instalador não abrirá. O arquivo já foi baixado e permanece no aparelho.",
    "upd.022" to "PERMITIR",
    "upd.023" to "O download falhou — a conexão caiu ou o arquivo chegou incompleto. Tente novamente ou baixe pelo navegador.",
    "upd.024" to "TENTAR NOVAMENTE",
    "upd.025" to "NO NAVEGADOR",
    "cat.001" to "Catálogo de baralhos",
    "cat.002" to "As frases vêm do Tatoeba e as formas das palavras, do Wikcionário. A licença e os créditos são exibidos antes do download.",
    "cat.003" to "CARREGANDO A LISTA…",
    "cat.004" to "A lista não chegou — não há rede ou a página do catálogo está inacessível. Nada quebrou: o baralho no aplicativo e a criação de baralhos com um modelo continuam onde estavam.",
    "cat.005" to "PÁGINA DO CATÁLOGO",
    "cat.006" to "TENTAR NOVAMENTE",
    "cat.007" to "O que aprender",
    "cat.008" to "Significados em",
    "cat.009" to "Tema",
    "cat.010" to "Nível",
    "cat.011" to "TODOS",
    "cat.012" to "Este par é bem atendido: o corpus contém muitas frases e os baralhos são grandes.",
    "cat.013" to "Este par tem pouco material: o corpus contém poucas frases, então os baralhos ficam menores. É um limite da fonte, não do aplicativo.",
    "cat.014" to "Ainda não há nada para este par. O README do projeto lista o nível de cobertura de cada par.",
    "cat.015" to "cartões",
    "cat.016" to "Licença: ",
    "cat.017" to "Fonte: ",
    "cat.018" to "BAIXAR",
    "cat.019" to "BAIXANDO",
    "cat.020" to "O download falhou — a conexão caiu ou o arquivo chegou incompleto. Nada foi instalado; é possível tentar novamente.",
    "cat.021" to "O arquivo chegou, mas não foi possível criar nenhum cartão a partir dele. Nenhum baralho foi adicionado.",
    "cat.022" to "Concluído. Cartões no baralho: ",
    "cat.023" to "MONTANDO O BARALHO…",
    "cat.024" to "MB",
    "cat.025" to "CC BY-SA: um baralho criado a partir deste e repassado mantém a mesma licença. Estudá-lo não impõe obrigação alguma.",
    "cat.026" to "Lista criada: ",
    "cat.027" to "iniciante",
    "cat.028" to "intermediário",
    "cat.029" to "avançado",
    "cat.030" to "Nada corresponde a estes filtros.",
    "cat.031" to "Um baralho pronto",
    "cat.032" to "Se conversar com um modelo não valer o esforço: um baralho do catálogo, frases escritas por pessoas, licença aberta e autoria identificada.",
    "cat.033" to "ABRIR O CATÁLOGO",
    "cat.034" to "JÁ BAIXADO",
    "cat.035" to "baixar novamente",
    "cat.036" to "MOSTRAR EXEMPLOS",
    "cat.037" to "CARREGANDO EXEMPLOS…",
    "cat.038" to "TENTAR OS EXEMPLOS NOVAMENTE",
    "cat.039" to "EXEMPLOS DO BARALHO",
    "cat.040" to "CARTÃO ",
    "cat.041" to "Com pronúncia",
    "a11y.011" to "Pesquisar baralhos",
    "src.001" to "Fonte · ",
    "src.002" to "Este cartão está errado?",
    "src.003" to "O cartão será ocultado, e um relatório pronto para colar, com o texto e o link da fonte, será copiado. Ele pode ser colado nas Issues do GitHub.",
    "src.004" to "OCULTAR E COPIAR",
    "src.005" to "CANCELAR",
    "src.006" to "Cartão ocultado · relatório copiado",
    "src.007" to "FONTE",
    "search.001" to "Pesquisar baralhos",
    "search.002" to "Pesquisa somente nos baralhos já instalados neste telefone. A rede não é usada.",
    "search.003" to "Expressão, frase ou tradução",
    "search.004" to "PESQUISAR",
    "search.005" to "PESQUISANDO…",
    "search.006" to "Digite pelo menos dois caracteres.",
    "search.007" to "Nada foi encontrado nos baralhos instalados.",
    "search.008" to "Os primeiros 80 resultados são exibidos — torne a busca mais específica para reduzir a lista.",
    "search.009" to "A pesquisa não foi concluída. Nenhum dado foi alterado; é possível tentar novamente.",
    "search.010" to "BARALHO · ",
    "mig.001" to "Atualizando o cronograma",
    "mig.002" to "Os baralhos e o histórico permanecem onde estão. As respostas são processadas novamente pelo FSRS-6 uma única vez.",
    "mig.003" to "O cronograma não foi atualizado",
    "mig.004" to "Nada foi excluído: os baralhos e o histórico continuam aqui. O reprocessamento pode ser tentado novamente com segurança.",
    "mig.005" to "TENTAR NOVAMENTE",
    "diag.001" to "Diagnóstico",
    "diag.002" to "Somente um resumo técnico: sem nomes de baralhos, textos de cartões ou histórico. Nada é enviado.",
    "diag.003" to "MOSTRAR DIAGNÓSTICO",
    "diag.004" to "OCULTAR DIAGNÓSTICO",
    "diag.005" to "COLETANDO…",
    "diag.006" to "COPIAR O RESUMO",
    "diag.007" to "Diagnóstico copiado",
    "diag.008" to "Não foi possível coletar o diagnóstico",
    "anki.001" to "Do Anki",
    "anki.002" to "Escolha um arquivo .apkg. Tudo permanece neste telefone.",
    "anki.003" to "Qualquer .apkg do Anki funciona, antigo ou novo.",
    "anki.005" to "ESCOLHER .APKG",
    "anki.006" to "LENDO O ARQUIVO…",
    "anki.007" to "Você pode sair desta tela; a importação continua.",
    "anki.008" to "Baralhos: ",
    "anki.009" to "Cartões: ",
    "anki.010" to "Eventos de revisão adicionados: ",
    "anki.011" to "Eventos de revisão ignorados: ",
    "anki.012" to "Suspensos ou enterrados no Anki, não adicionados: ",
    "anki.013" to "Cartões ignorados: ",
    "anki.014" to "Com imagens ou som: ",
    "anki.015" to "O histórico é muito grande: foram usadas as 100.000 avaliações mais recentes.",
    "anki.016" to "CONCLUÍDO",
    "anki.017" to "IMPORTAR OUTRO",
    "anki.018" to "Não foi possível ler este .apkg.",
    "anki.019" to "O pacote não contém uma coleção do Anki.",
    "anki.020" to "Não foi possível ler esta coleção. Nenhum dado foi alterado.",
    "anki.021" to "O arquivo está corrompido ou o formato ainda não pode ser lido.",
    "anki.022" to "O pacote ultrapassa o limite seguro de 300 MB. Nenhum dado foi alterado.",
    "anki.023" to "O pacote não contém cartões de texto legíveis. Nenhum dado foi alterado.",
    "anki.024" to "Nada mudou — corrija a exportação e tente novamente.",
    "anki.025" to "O que foi importado",
    "anki.026" to "Traga um .apkg pelo telefone: baralhos e histórico de avaliações, sem precisar reconstruí-los à mão.",
    "anki.027" to "IMPORTAR DO ANKI",
    "anki.028" to "O cronograma é reconstruído aqui; os intervalos do Anki não são transferidos.",
    "anki.029" to "O arquivo original do Anki não é alterado.",
    "anki.030" to "Recuperados dos campos: ",
    "anki.031" to "Este arquivo contém apenas o cartão “atualize o Anki”. Exporte-o novamente pelo Anki.",
    "anki.032" to "Idiomas: ",
    "anki.033" to "assunto",
    "anki.034" to "sem nome",
    "pc.001" to "Ainda não disponível no computador",
    "pc.002" to "Espaço revela, 1–4 avaliam, Z desfaz",
    "pc.003" to "Sessão",
    "pc.004" to "Escolha um baralho à esquerda",
    "pc.005" to "Arquivo",
    "pc.006" to "Exibir",
    "pc.007" to "Ajuda",
    "pc.008" to "Sair",
    "pc.009" to "Tela cheia",
    "pc.010" to "Atalhos de teclado",
    "pc.011" to "Pasta de dados",
    "pc.012" to "A Ikna já está em execução",
    "pc.013" to "A Ikna encontrou um erro. Os detalhes estão no arquivo de registro:",
    "pc.014" to "Arraste o cartão: esquerda significa não sei; direita, sei",
    "pc.015" to "Baralhos",
    "pc.016" to "Hoje",
    "pc.017" to "Minimizar janela",
    "pc.018" to "Maximizar janela",
    "pc.019" to "Restaurar janela",
    "pc.020" to "Fechar janela",
    "bk.001" to "UM ARQUIVO",
    "bk.002" to "SALVAR EM ARQUIVO",
    "bk.003" to "RESTAURAR DE UM ARQUIVO",
    "bk.004" to "ARQUIVO PARA O TELEFONE",
    "bk.005" to "PROCESSANDO…",
    "bk.006" to "Salvo: ",
    "bk.007" to "Respostas: ",
    "bk.008" to "Baralhos: ",
    "bk.009" to "Respostas importadas: ",
    "bk.010" to "Já presentes: ",
    "bk.011" to "Cartões recalculados: ",
    "bk.012" to "Configurações aplicadas",
    "bk.013" to "Arquivo não lido",
    "bk.014" to "Nada para salvar",
    "bk.015" to "Ler um arquivo completo",
    "bk.016" to "Respostas, configurações e textos dos baralhos — tudo o que não pode ser recriado.",
    "bk.017" to "Por que não há conflitos",
    "bk.018" to "O registro de respostas só recebe novos itens, e cada resposta é identificada pelo cartão e pelo horário. Mesclar dois registros é fazer uma união, portanto um arquivo pode viajar entre o telefone e o computador quantas vezes você quiser.",
    "bk.019" to "A restauração no telefone lê estes dois arquivos.",
    "bk.020" to "Ler um registro de respostas",
    "bk.021" to "Ler configurações",
    "bk.022" to "Ler um baralho",
    "bk.023" to "Arquivo: ",
    "bk.024" to "Tamanho, MB: ",
    "grading.001" to "Avaliações derivadas · experimental",
    "grading.002" to "Desativado por padrão. Usa somente seus tempos locais após o aquecimento. Benefício não comprovado; os intervalos são limitados a ±30%. Uma revelação obrigatória nunca conta como consulta opcional nem como evidência para Fácil.",
    "optimizer.001" to "Ajuste local do FSRS",
    "optimizer.002" to "Verifica previsões recentes de recordação usando apenas o histórico deste dispositivo, não constantes pessoais de memória.",
    "optimizer.003" to "Usar o ajuste aplicado",
    "optimizer.004" to "Calcular pelo histórico",
    "optimizer.005" to "Cancelar cálculo",
    "optimizer.006" to "Aplicar resultado salvo",
    "optimizer.007" to "Ainda não há cálculo.",
    "optimizer.008" to "Histórico insuficiente: {count} / 500 respostas avaliadas. Repetições com menos de um dia não são avaliadas.",
    "optimizer.009" to "Nenhuma melhora em relação aos padrões no histórico recente. Isso é normal, não é uma falha sua.",
    "optimizer.010" to "Previsões melhores nos dados de validação. Aplicar este resultado é uma escolha separada.",
    "optimizer.011" to "Calculando localmente em segundo plano. Você pode sair desta tela.",
    "optimizer.012" to "Somente respostas futuras. As datas existentes e o histórico permanecem inalterados. Desativar restaura os padrões imediatamente.",
    "optimizer.013" to "Respostas avaliadas",
    "optimizer.014" to "Último cálculo",
    "optimizer.015" to "Perda na validação: padrões / ajuste; menor é melhor",
    "optimizer.016" to "Próximo cálculo completo após {date}; no máximo uma vez a cada 30 dias.",
    "optimizer.017" to "Não foi possível ler ou salvar a configuração ou o resultado. Nenhum peso não validado foi ativado.",
    "optimizer.018" to "O cálculo falhou; o modelo aplicado permanece inalterado.",
    "optimizer.019" to "O histórico mudou durante o cálculo. Nada foi salvo; tente novamente.",
    "optimizer.020" to "Cancelado; o resultado salvo permanece inalterado.",
    "optimizer.021" to "Os pesos padrão do FSRS estão ativos.",
    "optimizer.022" to "O ajuste local aplicado explicitamente está ativo.",
    "optimizer.023" to "Resultado aplicado calculado em {date}.",
    "optimizer.024" to "Os ajustes completos são limitados a uma vez a cada 30 dias.",
    "optimizer.025" to "Candidato aceito salvo em {date}.",
    "browse.001" to "VISUALIZAR",
    "browse.002" to "DESLIZE PARA A DIREITA →",
    "browse.003" to "Isso é tudo por hoje",
    "browse.004" to "A Visualização volta após o próximo plano diário.",
    "browse.005" to "SEM AVALIAÇÃO",
    "browse.006" to "Ainda não há nada para visualizar",
    "browse.007" to "Cartões familiares aparecerão aqui depois de algumas revisões.",
    "a11y.012" to "Visualizar baralho",
    "a11y.013" to "Próximo cartão",
    "file.001" to "Substituir o arquivo existente?",
    "set.149" to "PORTUGUÊS (BRASIL)",
    "pseudo.001" to "Pseudolocalização",
    "pseudo.002" to "Expande somente o texto da interface para revelar cortes e layouts apertados. Não altera cartões nem baralhos.",
    "browse.008" to "Conclua primeiro todo o plano diário.",
    "browse.009" to "O limite da Visualização ainda não foi acumulado. Cada três cartões obrigatórios de planos concluídos rendem um cartão de Visualização.",
    "browse.010" to "Este baralho ainda não tem cartões familiares. Eles aparecem após duas revisões corretas em dias diferentes.",
    "browse.011" to "O limite diário da Visualização foi atingido. Ele será verificado novamente após o próximo plano diário.",
    "browse.012" to "O limite noturno está ativo. A Visualização será verificada novamente quando ele terminar.",
    "browse.013" to "Primeiro é preciso reduzir a fila de revisões obrigatórias. A Visualização será verificada com o próximo plano.",
    "browse.014" to "Depois de uma pausa, as revisões normais vêm primeiro. A Visualização será verificada com o próximo plano.",
    "browse.015" to "Depois de vários dias tranquilos, um plano diário normal vem primeiro. A Visualização será verificada amanhã.",
    "browse.016" to "As respostas recentes ainda não estão estáveis o suficiente. Reforce-as primeiro no modo normal.",
    "browse.017" to "O modo de retorno está ativo. A Visualização será verificada com o próximo plano diário.",
    "browse.018" to "A carga de hoje já foi alta. A Visualização será verificada com o próximo plano diário.",
    "browse.019" to "Um limite de segurança está ativo hoje. A Visualização será verificada com o próximo plano diário.",
    "browse.020" to "Verificando a disponibilidade da Visualização…",
    "browse.021" to "Não foi possível verificar a disponibilidade da Visualização. Tente novamente.",
    "a11y.014" to "Fechar aviso",
    "a11y.015" to "Visualização indisponível",
    "progress.001" to "HOJE",
    "progress.002" to "BARALHO",
    "inspector.001" to "Inspetor de elementos",
    "inspector.002" to "Ao passar o cursor, mostra o nome interno e os limites do elemento no canto inferior direito. Apenas para ajustar a interface no computador.",
    "keys.001" to "TECLAS",
    "keys.002" to "Pressione o pequeno × e depois a nova combinação. Use de 1 a 3 teclas.",
    "keys.003" to "Não sei / esquerda",
    "keys.004" to "Sei / direita",
    "keys.005" to "Mostrar resposta",
    "keys.006" to "Avaliação: De novo",
    "keys.007" to "Avaliação: Difícil",
    "keys.008" to "Avaliação: Bom",
    "keys.009" to "Avaliação: Fácil",
    "keys.010" to "Desfazer resposta",
    "keys.011" to "PRESSIONE AS TECLAS",
    "keys.012" to "MAIS",
    "keys.013" to "OCULTAR",
    "keys.014" to "RESTAURAR ANTERIOR",
    "keys.015" to "Use no máximo três teclas",
    "keys.016" to "Essa combinação já está em uso",
    "keys.017" to "Essa combinação é reservada pelo aplicativo",
    "keys.018" to "Pressione uma tecla comum, não apenas modificadores",
    "keys.019" to "Alterar combinação",
    "keys.020" to "Esc cancela a entrada",

)
